### ISSUE TITLE
Add version list to purl display

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/purl#1038]
Based on the design for the version list: https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=215-2&viewport=-12727%2C-3675%2C1&t=Q8XjDGjx2EhhCXEa-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=215%3A2

Add the version list to the right sidebar of the object display:

- [ ] Versions listed in descending numerical order
- [ ] Indicate which version is currently being displayed
- [ ] Show which version is currently being displayed
- [ ] Include "View" links to the display of each version

**Comment by jcoyne** [comment]
@astridu regarding the "Version" section in this mockup, what is this date? Where does it come from?  We don't use 2 digit years elsewhere. Do we want to introduce that here?

**Comment by astridu** [comment]
I didn’t intend to change the date.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jcoyne** [comment]
@astridu Can you tell me where the data for these dates come from?

**Comment by astridu** [comment]
I’m sorry. I don’t know n

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amyehodge** [comment]
@jcoyne and @astridu I was going to answer the date question, but then realized it was more complicated than I thought. I was thinking this should be the accessioned date for the specific user version, but then realized if there are many system versions that have been associated with a user version, which date do we show?

I'm thinking right now we show the accessioned date for the system version that the user version is currently pointing to, but I'd like to check with @andrewjbtw to make sure this makes sense to him as well.

**Comment by astridu** [comment]
> @aaron-collier I think you want to reference Figma (not the old Invision links). I think this one is [here](https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?node-id=215-2&t=Vz9QmVt5R71Vn01c-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=215%3A2&show-proto-sidebar=1). Is that the right one @astridu ?

Yes, that is the correct link to the mockups. If you don't see it, you can click the box icon in the top left to display the left nav so you can get to all the mockups.

**Comment by andrewjbtw** [comment]
> I'm thinking right now we show the accessioned date for the system version that the user version is currently pointing to, but I'd like to check with @andrewjbtw to make sure this makes sense to him as well.

Yes, that should be the date. It does mean that the current version's date would be updated if the user updates it without creating a new user version.

**Comment by andrewjbtw** [comment]
Note that we don't currently send that date in the purl metadata.

**Comment by aaron-collier** [comment]
re: date discussion above - @andrewjbtw: the date that the version displayed was complete. @justinlittman: we have the closed RepositoryObjectVersion.closed_at.

**Comment by jcoyne** [comment]
@astridu what happens if you click on the "Cite" link next to a version in this mockup?

**Comment by astridu** [comment]
I made a couple updates. I forgot we had updated 'Cite' to 'Copy URL' to make it more clear. I also changed the date format. Can we do the abbreviated month or do we need to show the whole month? https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=215-2&viewport=-12727%2C-3675%2C1&t=Q8XjDGjx2EhhCXEa-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=215%3A2

**Comment by jcoyne** [comment]
@astridu we can show whatever you want it to be.

**Comment by andrewjbtw** [comment]
Screenshot of design for version list when a version has been withdrawn
![version-list-purl-withdrawal](https://github.com/user-attachments/assets/fd32a691-2974-497d-800a-a03dc8ec319f)
