### ISSUE TITLE
Update display to use versioned metadata

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/purl#1039]
With versioned metadata available, the purl display will need to be updated to use the metadata for the version provided, or the latest version if not provided.

Add an optional version parameter to the purl URL that will be used for direct linking into a version and citations with version information.

**Comment by astridu** [comment]
Mockup
https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=215-3&viewport=-12727%2C-3675%2C1&t=Q8XjDGjx2EhhCXEa-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=215%3A3&show-proto-sidebar=1

**Comment by jcoyne** [comment]
Some of this is done by https://github.com/sul-dlss/purl/pull/1068

**Comment by mjgiarlo** [comment]
@jcoyne @cbeer What mechanism should purl use to interrogate what all versions are available for a given druid?

**Comment by jcoyne** [comment]
I was thinking the version manifest. Are there any other options?

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> I was thinking the version manifest. Are there any other options?

I don't know, but the version manifest sounds promising. @justinlittman confirm/deny/amend?

**Comment by justinlittman** [comment]
Confirm. Version manifest also records the date for the version and whether it is withdrawn.
