### ISSUE TITLE
Purl index page regression.

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/purl#1072]
We're no longer getting the object titles on https://purl.stanford.edu 
![Screenshot 2024-07-18 at 13 01 15](https://github.com/user-attachments/assets/794042a3-81b7-47aa-ba83-c0e8598191bf)

This seems like a regression introduced by https://github.com/sul-dlss/purl/pull/1054.

**Comment by andrewjbtw** [comment]
To add detail: instead of the druid, the link text should be the object title
