### ISSUE TITLE
Purl must have an endpoint to show the public cocina for a version.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/purl#1077]
This will be used by Stacks to retrieve the metadata.

If the version provided in the request is "1", but there is no versioned store for the object, then fall back to the legacy storage.
If the version provided is not one, use the versioned storage.
Return a 404 response if the requested version is not in storage.

**Comment by aaron-collier** [comment]
@jcoyne is this already done (https://github.com/sul-dlss/purl/blob/main/app/controllers/purl_controller.rb#L40)? Or is this a different endpoint need?

**Comment by jcoyne** [comment]
Yes, it looks like #1078 may have fixed this.
