### ISSUE TITLE
Support iiif manifest for book/image combination

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/purl#108]
The standard model for content-type=book is to have resources of type=page. But there was a time when we were migrating away from flipbook as the "book" reader to a more unified image viewer with book behaviors as we have today. To facilitate this, book-like objects have been digitized for awhile as content-type-book with resources of type=image. This worked in embed prior to cutting over to the new manifests, when the old viewer was reading content metadata directly.  Now embed brings up an empty viewer (because of content-type book) with "No images to display" (because there is no manifest created).

We would like to support the book/image combination for backward compatibility as we look at the body of material and decide whether to remediate the data or continue to embrace this as an alternate/simplified book model. We still prefer book/page because it does something different in assembly (better resource labels for instance) and provides a way to distinguish bound-page sequences from supplemental images.

The relevant code for deciding to make a manifest seems to be here:  https://github.com/sul-dlss/purl/blob/master/app/models/iiif_presentation_manifest.rb#L13-L21

**Comment by cbeer** [comment]
I'm not sure I understand what change is being requested -- do you have an example of such an object?

**Comment by LynnMcRae** [comment]
I had examples; shame on me for not including them.  Thanks to Ben here's a nice set of them:

From collection bx237rw7019 - Semiannual report to Congress
druid:zf119tw4418
druid:yr395qx7016
druid:vh661sw7791
druid:xd628vg3422

from collection ng056wy3948 - Semiannual report to the Congress
druid:xh307bp5065
druid:yy667gn7024

from collection druid:wf189dk1775 - Office of Inspector General semiannual report
druid:np594vr2488
druid:vk505dd1207
druid:wt743mq7975
druid:sh282tr9157
druid:ww404mj9924
druid:tk930rq1045
druid:ss494dm5787
druid:qf528hh1635

from collection druid:xn240hy3817 - Semiannual report to the Congress
druid:db718cv4515
druid:fb891mj6080
druid:tn904pf6928
druid:jw656tb9335

**Comment by LynnMcRae** [comment]
The change is to include resource types of both "page" and "image" for manifest/embed when content-type is book.  This is not only for the cases here where "image" was used where "page" is intended for historical reasons, but for more possible use cases where an image might be considered in addition to page. For instance, the image of a book's spine and covers could be coded as resource-type image rather than page, though we have not implemented that in practice. IIIF will have a similar situation for media where we do have supplemental images along with audio and video.
