### ISSUE TITLE
Investigate how metrics for purl pages will work with versioning and document

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#1090]
We need to think about how the metrics (views and downloads) on the purl pages will work when versioning is released to production. 

Requirement [here](https://docs.google.com/spreadsheets/d/1G2ixA4FS6e3ju0KlpPt9qLGd66EP0Vw-_umEauJxKe8/edit?gid=0#gid=0) on line 26:
Metrics that are displayed on the purl itself should continue to show aggregate statistics from across all versions.

We should make sure we know how this works, and then Amy needs to update the [public-facing documentation](https://sdr.library.stanford.edu/sdr-metrics) on metrics (and the [internal documentation](https://docs.google.com/document/d/1KNcj6sRrYnSZYe7Mp_vQc3XCUTe-vaFwVah8qXkEDD4/edit#heading=h.2bb9pp37bmdu)) should be updated to reflect this.

**Comment by jcoyne** [comment]
@amyehodge that's right. We discussed not breaking it out by version. Stats are still per-object.

**Comment by amyehodge** [comment]
From @andrewjbtw: What’s unclear is what changes (if any) are needed to keep the metrics showing the aggregate stats. Also, what changes might be wanted for the file-specific tracking we do behind the scenes?

And we need to review the display on PURL to make sure the language still makes sense.

**Comment by jcoyne** [comment]
No changes are needed to keep the metrics showing the aggregate stats.  I don't see any need to change file specific tracking behind the scenes unless there is some articulated business need.

**Comment by amyehodge** [comment]
@jcoyne Just so I'm clear, my recollection is that we are tracking downloads for each individual file already, but we are aggregating those for display on stacks. Is that correct? Thanks.

We should still doublecheck during testing that the displays on purl are showing what we think they should.

**Comment by jcoyne** [comment]
@amyehodge what do you mean by "each individual file"?  If you mean the combination of druid and filename, I believe that is correct.  If you mean druid/version/filename, then no.

**Comment by amyehodge** [comment]
Sorry for the lack of clarity @jcoyne . Yes, I meant the combination of druid and filename. Thanks.

**Comment by justinlittman** [comment]
@amyehodge From a code read, the existing functionality is not changing with versions. I'll assign this ticket to you do decide if additional testing is necessary and/or when it can be closed.
