### ISSUE TITLE
Do not display full public cocina/xml for withdrawn versions

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/purl#1091]
When a version is withdrawn, we show a tombstone page: https://sul-purl-stage.stanford.edu/tm662fj8161/v1

We should not show the whole cocina or public xml, which is still being served: https://sul-purl-stage.stanford.edu/tm662fj8161/v1.json

**Comment by aaron-collier** [comment]
@andrewjbtw what should the response be when requesting the json? Redirect to the tombstone or a 404...?

**Comment by andrewjbtw** [comment]
Redirect to the tombstone.

**Comment by jcoyne** [comment]
What if stacks or the embed viewer tries to retrieve the withdrawn json.  We shouldn't redirect these requests to the HTML page as that would break the parsing of the expected return. Shouldn't there be some some sort of minimal cocina or public xml that is returned?

**Comment by aaron-collier** [comment]
How about something minimal like:

```
{
  "cocinaVersion": "0.75.0",
  "type": "https://cocina.sul.stanford.edu/models/object",
  "externalIdentifier": "druid:wp335yr5649",
  "label": "Code and Data supplement .....",
  "version": 4,
  "status": "withdrawn"
}
```

**Comment by andrewjbtw** [comment]
Sure, it would be ok to return just that minimal data. The metadata will be available for the other versions, so we don't have to hide all of it.

**Comment by jcoyne** [comment]
@aaron-collier I'd be okay with that, but we may need an empty structural (with `contains: []`) in there too.

**Comment by aaron-collier** [comment]
@jcoyne ah yeah, probably a good idea to include that (and any other base keys) as empty.
