### ISSUE TITLE
Do not link to purl.stanford.edu from the header of purl pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/purl#1096]
We should remove the link to purl.stanford.edu from the header of purl pages. Adding that link was a recent change, I believe.

The purl.stanford.edu landing page does not function as a home page for Purl. As that page currently stands, sending people there does not provide much in the way of useful information for SDR users.

The text under the link also says "Stanford Digital Repository" so it might be a bit of surprise to be taken to a page about Purl instead. This also raises questions about the SDR's "branding" but that's a bigger picture discussion.

See [this Slack thread](https://stanfordlib.slack.com/archives/C07CQLENZGW/p1722636033205939) for additional background.

**Comment by jcoyne** [comment]
@astridu should the link go to https://sdr.stanford.edu/ instead?  I believe that not having a link compromises the component library as this will be a link on every other site that uses the components, but not this one.

**Comment by astridu** [comment]
@andrewjbtw What do you think? We could also send them to SearchWorks with the SDR facet selected.

**Comment by amyehodge** [comment]
To add my unsolicited opinion, sdr.stanford.edu does not seem like the right link to me. I like @astridu 's idea much better.

**Comment by andrewjbtw** [comment]
Any link on a purl page header is going to be disorienting, with sdr.stanford.edu being least appropriate to most of the content with purls. The SearchWorks facet at least brings in more content that has purls, but it still doesn't really work because people in SW won't come back to purls. SW has its own pages for all those items, but any links back to purl pages are buried in the SW interface. So why would anyone expect clicking at the top of purl to take you to SW? Especially if you clicked from one the purls that isn't in SW at all?

If we have to show a link, only purl.stanford.edu gives some indication of why the header link sent you there. The purl landing page could, if redesigned, send you to those other links with some context for why you might go to those other pages.

**Comment by astridu** [comment]
@andrewjbtw Would you be ok w/keeping the link as is if we can redesign that landing page later this year?

**Comment by andrewjbtw** [comment]
If we have to have a link because some template requires it, yes, the purl landing page is ok as the least irrelevant of possible links we could put there.
