### ISSUE TITLE
IIIF Manifests @id can be non spec compliant.

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/purl#122]
According to the [IIIF spec](http://iiif.io/api/presentation/2.1/#id)

```
A manifest must have exactly one id, and it must be the http(s) URI at which it is published.
```

We allow our the IIIF manifest to be returned under the following URLs:
- https://purl.stanford.edu/fw090jw3474/iiif/manifest
- https://purl.stanford.edu/fw090jw3474/iiif/manifest.json

However; the URL returned in the `@id` parameter is always `https://purl.stanford.edu/fw090jw3474/iiif/manifest`.  This is causing some issues with some 3rd party software that implements the IIIF spec.

One possibility would be to use `controller.request.original_url` instead of `iiif_manifest_url` [here](https://github.com/sul-dlss/purl/blob/master/app/models/iiif_presentation_manifest.rb#L56)

If that sounds agreeable, I'm happy to submit a PR with that change (as this could potentially cause some issues with a demo we have next week if somebody adds the `.json` in their manifest URLs).

**Comment by LynnMcRae** [comment]
I note that we are not actually responding to .json as a suffix but simply ignoring suffixes.  .xml or .popsicle or .anything all respond with the same manifest.  Is it too late to stop recognizing any variation (I am guessing it is).

**Comment by jkeck** [comment]
Ah, that's very interesting, and potentially puts us in a pickle.

I wonder if we can do some log analysis to see how prevalent the use of `.json`, as well as other random extensions, is for our manifests.  I'm not sure when I got in the habit of doing that, and maybe the use of the `.json` extension is primarily constrained to a few internal uses (although it may be difficult to tell where the requests are getting their manifest urls from).

One potential solution, based on the results of that analysis, could be to allow `.json` as a legacy (and do a permanent redirect) to `/manifest` and update our local software that has been using the extension. (already filed sul-dlss/sul-embed#744)
