### ISSUE TITLE
Create a IIIF Presentation Manifest builder for v3 (speculative) manifests

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/purl#132]
http://prezi3.iiif.io/api/presentation/3.0/

Checklist moved to https://github.com/sul-dlss/osullivan/issues/1 

----

A/V stuff:

- [x] Add duration to support time (http://prezi3.iiif.io/api/presentation/3.0/#duration)
- [x] Add a new `viewingHint` value of "auto-advance"
- [x] Add new property `timeMode` (http://prezi3.iiif.io/api/presentation/3.0/#timemode)
- [ ] A/V support https://github.com/IIIF/iiif-av/blob/master/source/api/av/index.md#av-description-in-the-presentation-api

---

Out of scope:

- [x] Add new property `choiceHint` (http://prezi3.iiif.io/api/presentation/3.0/#choicehint)
- [x] Add a new `viewingHint` value of "together"
- [ ] Consider JSON-LD Language Maps 
- [ ] Use and explain the import of the Web Annotation context

**Comment by ndushay** [comment]
Are we doing A/V support, or is this ticket done now?

**Comment by cbeer** [comment]
At standup today, I think we established that we should look into A/V support enough to provide feedback to the iiif-discuss list. I tried to tackle some of the easy things (adding properties and legal values) in https://github.com/sul-dlss/osullivan/pull/13.
