### ISSUE TITLE
"publish" v3 iiif manifests for "pdf objects"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/purl#145]
- [ ] how do we know when we have a "pdf object"?   Is it a non-image, non-media object with a pdf?   What if there are images and pdf, or media and pdf?  or xxx and pdf?

- [ ] purl app uses iiif3  routes for ^^ object presentation manfests

is this covered in #133 ?

**Comment by cbeer** [comment]
> how do we know when we have a "pdf object"? 

Maybe a better way to rephrase the task is "include PDFs in the v3 IIIF manifests"? We shouldn't need to care if it is a "PDF object" or not.

PURL doesn't consume the IIIF manifests either -- that's done over in sul-embed.

**Comment by ndushay** [comment]
okay, maybe I don't understand this well enough, but "implement v3  (UV flavor)  iiif  manifests for everything" seems like a bigger task than focusing on one type of data first.

**Comment by blalbrit** [comment]
per @LynnMcRae (https://consul.stanford.edu/pages/viewpage.action?title=DOR+content+types%2C+resource+types+and+interpretive+metadata&spaceKey=chimera)

Proposed content types (in progress)
for content-type=document, resource types are:
document – must contain a file that is supported for viewing, starting with PDF (any requirements, limitations?).  Other types may be added in the future. 
alternative model: distinguish resource-type to correspond with different types of docs.  
for content-type=3d, resource types are:
3d -- in progress, samples files at http://web.stanford.edu/~cengel/3D/bf418ns2590/

**Comment by blalbrit** [comment]
note ^^ have not been implemented yet, but we can do with the fixture objects if @LynnMcRae says this is stable enough to proceed with.

**Comment by jmartin-sul** [comment]
duplicates #147

feel free to reopen if that seems incorrect
