### ISSUE TITLE
error producting iiif3 multi-image manifest:

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/purl#157]
https://purl.stanford.edu/bc151bq1744/iiif3/manifest

`SyntaxError: JSON.parse: end of data after property value in object at line 8334 column 9 of the JSON data`

**Comment by cbeer** [comment]
I'm not seeing a problem using `json_pp` or loading it up in ruby. Where are you seeing that error?

**Comment by ndushay** [comment]
in my browser.

**Comment by cbeer** [comment]
What browser? This is working fine for me:

```
result = $.get("https://purl.stanford.edu/bc151bq1744/iiif3/manifest.json");
JSON.parse(result.responseText);
```

**Comment by ndushay** [comment]
working for me too, now.  (it was firefox).  Tommy witnessed the error in our screen hero session -- dunno if anything changed between yesterday afternoon and today.  I think he mentioned working on something or other with Ben ...
