### ISSUE TITLE
Presentation manifest for book/manuscript should include viewingDirection

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/purl#165]
Content Metadata for type=book can include a <bookData> tag with an attribute to indicate reading direction, to wit (https://purl.stanford.edu/yr183sf1341):

```
<contentMetadata type="book" objectId="yr183sf1341">
     <bookData readingOrder="rtl"/>
```
"ltr" is the default, likely never to be explicitly expressed. "rtl" as shown here should translate to a `<viewingDirection>` value of "right-to-left" in the presentation manifest for books (or manuscripts).

**Comment by ndushay** [comment]
So is this supposed to DEFAULT to "left-to-right" explicitly expressed in the code??  @LynnMcRae @tingulfsen ?

**Comment by LynnMcRae** [comment]
Not sure what the question is asking. The IIIF spec says the manifest MAY have a viewing direction, though it is silent on what default behavior a viewer might exhibit in its absence.  In content metadata we have only expressed readingOrder="rtl" assuming a default of ltr/left-to-right in our local viewers, but I was thinking we would always express viewingDirection in the manifest for book to make it explicit either way, for a global audience.

**Comment by LynnMcRae** [comment]
yes, it should always express viewingDirection for book. However there are three cases possible in contentMetadata/bookData -- explicit readingOrder=rtl, explicit readingOrder=ltr, and no readingOrder (default left-to-right).
