### ISSUE TITLE
IIIF v3 requires 'items' (but UniversalViewer of 2017-07-19 can't cope)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/purl#167]
NOTE:  as of 2017-07-19 UniversalViewer only understands `sequences` and `canvases`, not items.  Some discussion is ensuing within Digerati as to whether UV will be updated to also accept `items`

per http://prezi3.iiif.io/api/presentation/3.0 
- [ ] manifests have `items`, not `sequences` (per v3 spec)
- [ ] sequences have `items`, not `canvases` (per v3 spec)
- [x] thumbnail must be an array (per v3 spec) -- addressed with #171 and #172

This ticket started as related to sul-dlss/osullivan#22, sul-dlss/osullivan#24:

**Comment by cbeer** [comment]
We should validate that UV supports `items`; it looks like that may be a recent change in the draft spec.

**Comment by ndushay** [comment]
absolutely agree -- or I would have prepared a PR already

**Comment by jmartin-sul** [comment]
tested using http://universalviewer.io/examples/, and the following manifests:
https://gist.github.com/jmartin-sul/30624aedb667f91df1dae9fa9181aa50/revisions

UV seems fine with `thumbnail` as an array (or at least that behaves the same as the original unedited manifest).  it does not seem to like when `sequences` and `canvases` get replaced by `items`.  the first revision is the one with all the changes being tested, the second revision is just `thumbnail` as an array, the third revision is the original unedited manifest.json (copied from https://purl.stanford.edu/bc592pz8308/iiif3/manifest).

behaved the same in chrome and safari (didn't work in FF, which was my recollection from when i was using http://universalviewer.io/examples/ to test some manifest changes i paired with @cbeer on a couple weeks ago).

**Comment by ndushay** [comment]
thanks, @jmartin-sul .   @cbeer  Can we get UV to also take "items"?  It's actually clear in the 3.0 docs - the info about Canvas in the av updates doc at https://github.com/IIIF/iiif-av/blob/master/source/api/av/index.md and the Manifest and Sequence section in the 3.0 draft spec  http://prezi3.iiif.io/api/presentation/3.0/#sequence.

**Comment by jmartin-sul** [comment]
updated the gist to replace only `sequences` with `items`, and then to replace only `canveses` with items, but UV didn't like those either.

**Comment by cbeer** [comment]
Yeah, again, I'm not surprised. The change to use `items` everywhere seems it was made after we started our work. I think we should check with Ed to see what his plans are for updating UV.

**Comment by mejackreed** [comment]
UV does now support `items` only. Also we aren't using UV anymore. Closing this issue.
