### ISSUE TITLE
Add height and width properties to manifest thumbnail resources

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl#168]
```
 "thumbnail": {
    "@id": "https://stacks.stanford.edu/image/iiif/fw090jw3474%2Ffw090jw3474_00_0001/full/!400,400/0/default.jpg",
    "@type": "dctypes:Image",
    "format": "image/jpeg",
    "service": {
      "@context": "http://iiif.io/api/image/2/context.json",
      "@id": "https://stacks.stanford.edu/image/iiif/fw090jw3474%2Ffw090jw3474_00_0001",
      "profile": "http://iiif.io/api/image/2/level1.json"
    }
  },
```

should include `height` and `width` properties. Since we're dynamically resizing the image to 400 pixel long-edge (`!400,400`), I guess we'll need to adapt the scaling logic from stacks into purl?

---

When running our manifest through the validator 

http://iiif.io/api/presentation/validator/service/validate?version=2.0&url=https://purl.stanford.edu/fw090jw3474/iiif/manifest

```json
"error": "None",
"okay": 1,
"warnings": [
"WARNING: Resource type 'dctypes:Image' should have 'height' set\n",
"WARNING: Resource type 'dctypes:Image' should have 'width' set\n"
]
```

**Comment by cbeer** [comment]
It must be complaining about the thumbnail resource?

**Comment by mejackreed** [comment]
It looks that way.

**Comment by ndushay** [comment]
I would imagine it matters for all thumbnail resources, not just in manifests?
