### ISSUE TITLE
Should we modify the logic for how images are returned in a sequence?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl#181]
Currently our logic only returns files if they are "deliverable": https://github.com/sul-dlss/purl/blob/master/app/models/iiif_presentation_manifest.rb#L34

That logic being:

Stanford only rights OR World rights.

This logic _seems_ like it is ok, but I would offer it may be problematic in a case where we _can_ offer an image as metadata for 400 x 400. 

Examples of these types of objects are plentiful, but I will focus on https://purl.stanford.edu/zx774pr7698 as it is a map image from DRMC, which should be at least thumb viewable, no?

We are showing these in SearchWorks as thumbs (via Stacks delivery).. why can't we offer them as limited support as resources in the manifest?

cc @snydman

**Comment by mejackreed** [comment]
Proposal:

1. Use rule of thumb, to add thumbnail to the manifest
1. See if that fixes UV blowing up
1. If not, use rule of thumb to add thumbnail image as the first resource in the sequence

**Comment by aeschylus** [comment]
Assuming we don't want to share these CC resources fully, I'm for option 3.

Another option is to serve the proper manifest but restrict the image requests with the Auth pattern. This would be more consistent across objects.
