### ISSUE TITLE
Add PDF rendering to IIIF manifest for content with a PDF available

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl#193]
An example: https://wellcomelibrary.org/iiif/b1948799x/manifest

See "rendering" section

Our objects that have a PDF available should also have this section.

Druids:
 - `xt162pg0437 `

**Comment by LynnMcRae** [comment]
These are resources of type=object, which can be any type of file for download, but typically if not exclusively PDFs to date.

**Comment by snydman** [comment]
see http://iiif.io/api/presentation/2.1/#rendering
