### ISSUE TITLE
Content search service description points to wrong version of spec

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/purl#199]
The content search service description introduced in sul-dlss/purl#198 adds the service description to manifests like the following:

```json
{
  "service": [
    {
      "@context": "http://iiif.io/api/search/0/context.json",
      "@id": "https://exam.pl/cc842mn9348/search",
      "profile": "http://iiif.io/api/search/0/search",
      "label": "Search within this manifest"
    }
  ]
}
```

We should be implementing version 1.0 of the Content Search API, and thus have a service description more like the following:

```json
{
  "service": [
    {
      "@context": "http://iiif.io/api/search/1/context.json",
      "@id": "https://exam.pl/cc842mn9348/search",
      "profile": "http://iiif.io/api/search/1/search",
      "label": "Search within this manifest"
    }
  ]
}
```

See [§3.1 of the spec](http://iiif.io/api/search/1.0/#service-description) for more information.

**Comment by cbeer** [comment]
Blocked, I think, waiting for UV to support v1.0: https://github.com/UniversalViewer/universalviewer/blob/bd615a7c8316e003aab1ded09c4414906548e006/src/lib/manifesto.js#L466.

**Comment by anarchivist** [comment]
I just diffed the 0.9.3 and 1.0 specs, and the changes seem to be editorial - no changes in syntax or semantics, so this is not super pressing anyhow.
