### ISSUE TITLE
PURL metadata files

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/purl#22]
Right now, PURL only exposes a handful of the metadata files in the document cache (public xml, mods, and the IIIF manifest). In spot-checking some records, I noticed a handful of other files (contentMetadata, properties, etc) that seem to also be embedded in the public xml.

What is the relation between the metadata in the public XML and the stand-alone files?

Can we expose the stand-alone files, as we do the public xml, mods, etc?

@blalbrit?

**Comment by blalbrit** [comment]
@cbeer the public XML contains an aggregation of data pulled from the other streams on PURL document_cache - but pruned to only expose the information that should be made publicly available. 
 The contentMetadata contains all data about an object (both publicly available resources, and non-published non-public content). I would say no to exposing stand-alone files now - at least contentMD, but will check further.

There is likely some logic to why non-exposed streams are added to the document_cache, and I'll try to chase it down. The relevant block of code for publish is here: https://github.com/sul-dlss/dor-services/blob/87beb48f2911378fdc645fb593aeb91038fe8927/lib/dor/models/publishable.rb if that is helpful.

**Comment by cbeer** [comment]
> There is likely some logic to why non-exposed streams are added to the document_cache, and I'll try to chase it down.

Great, that would be really helpful. I'm (clearly) having trouble understanding how the various systems are interacting.
