### ISSUE TITLE
"Appears in" statement no longer displays for children of virtual objects

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/purl#223]
Previously, an "appears in" statement appeared on purl pages for children of virtual objects, linking the children to their parent:

Screenshot of https://purl.stanford.edu/hp623ch4433 from 8/28/2016:
![image](https://user-images.githubusercontent.com/7491842/39448928-83977ee6-4c7b-11e8-9e76-8d08b5e18815.png)

(Ignore the duplicate info  - that's a data issue that's being handled elsewhere.)

The same record today:
![image](https://user-images.githubusercontent.com/7491842/39449172-32ed1a40-4c7c-11e8-8a50-2de5882efbb6.png)

The statement is still present in the public MODS, but does not display on the purl page.

More examples:
https://purl.stanford.edu/tx980cm5270
https://purl.stanford.edu/mg049fq2728

Possibly related to the work done on how mods_display handles related items during the Parker Spotlight sprint. @blalbrit 

(Please let me know if this isn't the right place for this ticket.)

**Comment by caaster** [comment]
Hi @snydman - I'm very interested in having this ticket addressed during the next appropriate work cycle, whether that's a maintenance work cycle or something else. What's the best way for me to champion this ticket?

**Comment by caaster** [comment]
Hi @matienzo -- inquiries have been surfacing again about this ticket, specifically when it might be addressed. I'm tagging you as I imagine it is a first heard for you!
