### ISSUE TITLE
Non-javascript fallback for content

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/purl#23]
If we use the sul-embed widget for displaying content, I think we want provide a non-javascript fallback (although, I note that the current site doesn't work with javascript disabled). Is a simple file listing sufficient, or should we make other considerations?

Another option I can think of is providing a link to the content-embedded-without-javascript and let sul-embed worry about non-javascript compatibility..

@jvine?

**Comment by mejackreed** [comment]
-1 for having sul-embed worry about non JavaScript

**Comment by cbeer** [comment]
@mejackreed I don't disagree, although my thought was: if sul-embed is already parsing the contentMetadata and displaying a file list, I'd rather not copy that same logic into PURL.

**Comment by jkeck** [comment]
Apps could possibly link to PURL in a <noscript> or something (although I don't know if that really solves anything).

Not having SUL-Embed worry about non-js means that only apps that have intimate knowledge about the contentMetadata can have any sort of useful fallback behavior.  The only app that is likely to have knowledge about the contentMetadata of every object is PURL itself.  Perhaps that's fine, but it's a conscious decision that we have to make about how these objects will behave sans-js.

**Comment by mejackreed** [comment]
I can understand that @cbeer ... It could potentially work if PURL made and displayed the request server side

**Comment by thatbudakguy** [comment]
Closing since I think this properly belongs in sul-embed: we can manage to embed the thing if JS is off, we just need to delegate to the individual viewers to figure out what to do once that happens.
