### ISSUE TITLE
Use content negotiation "accept headers" to provide v2 or v3 manifests

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl#233]
https://iiif.slack.com/archives/C0AL6BU76/p1527793570000579

![screen shot 2018-05-31 at 1 12 51 pm](https://user-images.githubusercontent.com/1656824/40802960-63aa7892-64d4-11e8-8668-68631f1cd63a.png)

**Comment by cbeer** [comment]
What's a `v3` accept header look like?

**Comment by mejackreed** [comment]
The Accept header looks like:

`Content-Type: application/ld+json;profile="http://iiif.io/api/presentation/3/context.json"`

https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#63-responses

**Comment by mejackreed** [comment]
I think until UV supports content negotiation we still need to provide the v3 url and default to v2. But eventually this seems it will shake out.

In other news, Diva 6 supports this.

**Comment by mejackreed** [comment]
Also, we will need to update our cache keys to include the accept header. Also do we need to update Vary as to handle browser caching?

**Comment by mejackreed** [comment]
Likely we also need to verify that we support `OPTIONS` for both purl here and stacks requests.
