### ISSUE TITLE
Test PURLs for a variety content types and reading rules

### ISSUE THREAD

**Issue by snydman** [sul-dlss/purl#25]
See: https://docs.google.com/spreadsheets/d/1T4MY5jIUqd4XAnPgwiuKItOTBcTT8oVGHIulRE_ldP8/edit#gid=0

@jkeck @cbeer @mejackreed @aalsum @aeschylus

**Comment by snydman** [comment]
@mejackreed please add GIS examples to this spreadsheet? 

@aalsum please add Web Archive seed record examples?

**Comment by cbeer** [comment]
:+1:

**Comment by aalsum** [comment]
@snydman Can you give us write access?

**Comment by aalsum** [comment]
@snydman Webarchive-seed is added to the sheet.
