### ISSUE TITLE
Write copy for the purl index page

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/purl#26]
We'll need some real copy for the updated PURL index page:

<img width="599" alt="screen shot 2015-07-24 at 9 16 14 am" src="https://cloud.githubusercontent.com/assets/111218/8879177/a8906500-31e4-11e5-8754-55f0c6c87836.png">

I've cobbled together some content from some of the SDR services pages, but we can probably do better.

> The Stanford Digital Repository supports management of scholarly information resources of enduring value to Stanford University. Faculty, students, and researchers use SDR services to promote and protect the products of their work. Scholars around the world use content in the SDR in their research. The benefits of this service distinguish the SDR from other content storage or management options on campus: deposited content is preserved in a robust, reliable, and secure environment for access by scholars today and for generations to come.
> 
> Metadata describing the content is indexed for search and discovery in SearchWorks, and copies of ingested content are provided via persistent URLs (PURLs) to authorized users. The PURL itself is based on a unique SDR identifier, serving up a reliable, long-lived citation link.

**Comment by snydman** [comment]
@hannahfrost can you help with this?

**Comment by hannahfrost** [comment]
@snydman yes. Deadline?

**Comment by cbeer** [comment]
@hannahfrost no hurry (it's not like purl currently has an index page...)

**Comment by thatbudakguy** [comment]
this is done!
