### ISSUE TITLE
Reducing styling complexity and duplication

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl#27]
Happy to help out with this to move to consolidation. Starting a list here:
- [ ] If we do rely on sul-embed for file display logic, we can probably remove this type of stuff https://github.com/sul-dlss/purl/blob/cb6632a83ea7048a31269b827990aeebeadfe2f6/app/helpers/application_helper.rb#L106-L201
- [ ] move creative commons and other license images, classes to sul-styles (this is replicated styling/images used now in EW, SW, purl, and sul-embed) Probably also in hydrus

**Comment by cbeer** [comment]
I'm working on this in the `sw-design` branch, where the `application_helper` stuff is already ripped out. Right now, I've just dropped the searchworks css and layout into the application, but :+1: on consolidating on sul-styles.

**Comment by mejackreed** [comment]
:+1: great... also I can update sul-styles to add all of the icons that you added in `sw-design`. That might help clean up that branch some.
