### ISSUE TITLE
characters in a URL included in a metadata value cause active linking error

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/purl#292]
This object's metadata includes a DOI URL: https://purl.stanford.edu/qc071qw4486

There is a close parens in the DOI which is interfering with the active link as displayed on the PURL page.

The DOI in the metadata value is:
https://doi.org/10.1016/S0016-5085(18)34056-3

The active link only shows for:
https://doi.org/10.1016/S0016-5085(18

**Comment by jcoyne** [comment]
This is resolved.
