### ISSUE TITLE
Need to distinguish between 3.x and 4.x version of by-nc-nd

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/purl#321]
https://purl.stanford.edu/zs505gn5652

The rightsMD for this object calls out the 4.0 CC license, but the PURL returns the 3.0 CC license.

Ben A. says: "Note that by-nc-nd is coded, I think, for the 3.0 license. There needs to be some way to distinguish between 3.x and 4.x versions of by-nc-nd."

See also: https://github.com/sul-dlss/argo/issues/1394

**Comment by andrewjbtw** [comment]
Another example of this issue: https://purl.stanford.edu/xf457dx9166

The metadata has been updated to use the 4.0 license and that's what shows in the XML at https://purl.stanford.edu/xf457dx9166.xml but the PURL page is displaying and linking to the 3.0 license.

**Comment by cbeer** [comment]
PURL only looks at the value of the `//use/machine` element (by spec, I believe). If we want to support different values, we'll need a new spec (presumably using the `uri` values?)

**Comment by hannahfrost** [comment]
I believe you are right, @cbeer . If the machine element is omitted, PURL will display whatever is shown in the human element.

**Comment by jcoyne** [comment]
This is now resolved.
