### ISSUE TITLE
MODS display issue in test with LCSH terms w/ "--" delimiters

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/purl#34]
Submitted by Nicholas as https://jirasul.stanford.edu/jira/browse/PURL-122

In this test record: https://purl-test.stanford.edu/gb667dy0829 , subject terms are entered in the MODS like so: 

<subject authority="lcsh"> 
  <topic>Economic assistance, Domestic--United States--Statistics</topic> 
</subject> 

In purl-test, each term in the string is presented on a separate line, i.e., 

    Economic assistance, Domestic 
    United States 
    Statistics 

Pasting the full MODS of this record into http://mods-display.herokuapp.com/mods yields correctly-formatted LCSH subject term strings. Was this a deliberate change enforcing better-structured data or an unintentional regression?

(Not a deliberate change -lynn)

**Comment by cbeer** [comment]
I believe we inherited this display from SearchWorks, and should resolve this ticket there.

**Comment by LynnMcRae** [comment]
I'll look for a case where SW is displaying MODS instead of MARC to verify it has the same issue.

**Comment by LynnMcRae** [comment]
The problem seems to be the construction of multi-part subjects in general and is not confined to the pre-assembled topics with "--".  This example shows a fully structured multi-part subject:

   http://purl.stanford.edu/bs646cd8717.mods
  <subject authority="lcsh">
    <geographic>Europe</geographic>
    <topic>Civilization</topic>
    <temporal>18th century</temporal>
  </subject>

The parts are vertical in purl-test but correctly assembled into one line in SW test:
    http://searchworks-test.stanford.edu/gdor/view/bs646cd8717

The difference might be that SW creates search links out of the parts before assembly and PURL does not, so something might be missing in the latter pathway.  Given this, should this remain a PURL ticket?

**Comment by cbeer** [comment]
Thanks for the sleuthing. I think I've fixed this in fc9e9bdcd8645594fd096faa0a609b44c5823904, and am deploying to the various environments.
