### ISSUE TITLE
Validate our IIIF v3 manifests

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/purl#360]
Our IIIF v3 manifests are not valid. Most of this is caused by Strings that need to be Objects or Arrays.

https://iiif.io/api/presentation/validator/service

**Comment by cbeer** [comment]
Is the IIIF v3 spec finalized now? I think we gave up trying to hit the moving target.

**Comment by mejackreed** [comment]
Not yet officially. But in practice (for our validation issues) yes. Most of the issues are basically this String should be an Array/Object now which is a core concept well established for v3.
