### ISSUE TITLE
misaligned display of "preferred citation" and "collection" label and associated values near the top of a PURL page

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/purl#407]
The attached screenshot shows the misalignment of metadata displayed below the item title and above viewer. Here is a sample item: https://purl.stanford.edu/nw037gk9818

**Comment by mejackreed** [comment]
@hannahfrost the issue has been resolved in code we have not redeployed purl yet. Our weekly deploys go out on Monday mornings. Would it be useful to get this out today?

**Comment by hannahfrost** [comment]
Sure, Monday is fine. Thanks @mejackreed
