### ISSUE TITLE
Selected URI Pattern for IIIF Canvases

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/purl#44]
pattern should be: {druid}/iiif/canvas-{n} , where {n} starts with 1. per conversation with @azaroth42 and @LynnMcRae 

Should dereference the json fragment of the canvas as it appears within the manifest.json

**Comment by azaroth42** [comment]
To be clear:  {druid}/iiif/canvas-{n}  :)

**Comment by cbeer** [comment]
We intentionally decided not to embed any resource information in these urls? It seems like it would be  easier to (correctly) dereference the url if it was keyed on metadata instead of count-dependent (and be less vulnerable to adding or removing resources).

**Comment by azaroth42** [comment]
I don't think there was any strong intention here, other than lacking a guaranteed unique piece of metadata to generate the URI from for every canvas for every object. For example, an image might contain a depiction of multiple objects and hence multiple canvases, so using the image filename wouldn't work. There also might be no image for a canvas. Proposals would be welcome of course :)

**Comment by azaroth42** [comment]
And to clarify (I hope) the dereferencing requirement, when the Canvas's URI is dereferenced, the response should be JSON-LD and contain a description of the Canvas as it appears within the manifest.  It must also have the @context copied to the top of the json structure, resulting in something like the example here:  http://iiif.io/api/presentation/2.0/#canvas
