### ISSUE TITLE
Selected URI Pattern for IIIF Annotations

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/purl#45]
pattern should be: {druid}/iiif/canvas-n/annotations per conversation with @azaroth42 and @LynnMcRae 

This is a back-burner for now.

**Comment by azaroth42** [comment]
To clarify...

The URI pattern for Annotation __Lists_ (see http://iiif.io/api/presentation/2.0/#other-content-resources) could be `{druid}/iiif/canvas-{n}/annotations`.  The annotations in that list should be those that have `canvas-{n}` or part of it as their target.  However this limits implementation possibilities as canvas-{n} cannot be both a directory and a file (the JSON) at the same time.

The URI of the Annotations in that list has not been discussed, but I would propose one of:

  * {druid}/iiif/canvas-{n}/anno-{m}
  * {druid}/iiif/canvas-{n}/annotations/anno-{m}

My concern with the second is the same as with the current proposed pattern for lists.

**Comment by cbeer** [comment]
IIIF now recommends some URI patterns: http://iiif.io/api/presentation/2.1/#a-summary-of-recommended-uri-patterns

I suggested we move from our current IIIF annotation URI pattern of using sequential numbering for our canvas URIs to a more permanent URI structure using the resource id already present in the contentMetadata.
