### ISSUE TITLE
Google prevented from harvesting PURL pages

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/purl#454]
If you search for a purl in google, it'll return a purl page, but with no description:

<img width="435" alt="Screen Shot 2020-12-17 at 2 55 02 PM" src="https://user-images.githubusercontent.com/92044/102542789-ef990180-4077-11eb-9cfc-5965bcb2c2c3.png">

I think this is because robots.txt has:

```
# To ban all spiders from the entire site uncomment the next two lines:
User-Agent: *
Disallow: /
```

Is there a reason we have that robots.txt directive?

**Comment by mejackreed** [comment]
Yes a long standing policy decision SDR to do this. Defer to mgmt team about making changes to this policy decision.

**Comment by jcoyne** [comment]
@hannahfrost @amyehodge Can you shed some light on this policy?

**Comment by hannahfrost** [comment]
It was Lynn's (and Stu's?) vision that SDR PURLs should not be indexed directly via search engines, only via SearchWorks for SUL context or via some other publisher where the PURL was deliberately provided by the author/owner for discovery.

It is possible to imagine use cases where a depositor would want to publish their PURL with full control how/when/where it is picked up, leaving SearchWorks out of it. @amyehodge might have ready examples of those.

I am fully in favor of revisiting this policy and approach, as I believe it has hampered discovery for the majority of our depositors who expect it.

**Comment by thatbudakguy** [comment]
this is blocked on PO (and others) analysis on whether there are SDR objects that we would need to prevent being harvested on a case-by-case basis.

**Comment by lwrubel** [comment]
@vivnwong and @amyehodge will start working through policy considerations to permit this.
