### ISSUE TITLE
add support for externalFile references for IIIF manifest generation

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl#49]
This is for the virtual objects (atlases). See the old PR here: sul-dlss/dor-services#89

The specification is here: https://consul.stanford.edu/display/chimera/Support+for+virtual+resources

Here is the prototype object in production: https://argo.stanford.edu/catalog/druid:hj097bm8879

Took a cursory look at this issue and have the following list of tasks:
- [x] establish development environment on laptop
- [x] add fixture data for virtual parent object and children
- [x] add unit tests in `iiif_manifest_spec.rb` for virtual objects with only remote resources
- [x] change `ContentMetadata.extract_resources` to handle child objects from `externalFile` data
- [ ] change/verify dor-services (publish step) exports correct metadata for externalFiles (see https://github.com/sul-dlss/dor-services/pull/128)
- [x] PR review/merge
- [ ] migrate prod Rumsey virtual atlas to stage environment
- [ ] deploy to stage
- [ ] deploy to prod

**Comment by drh-stanford** [comment]
Took a cursory look at this issue and have the following list of tasks:

- [ ] establish development environment on laptop
- [ ] change `ContentMetadata.extract_resources` to handle child objects from `externalFile` element data
- [ ] add fixture data for virtual parent object and children
- [ ] add unit tests in `iiif_manifest_spec.rb` for virtual objects without file resources, and with mix of file and externalFile
- [ ] PR review/merge
- [ ] migrate prod Rumsey virtual atlas to stage environment
- [ ] deploy to stage
- [ ] deploy to prod

**Comment by cbeer** [comment]
I assume the outstanding tasks have all been done by now?

**Comment by drh-stanford** [comment]
yes, closing
