### ISSUE TITLE
Cocina fileSets are producing IIIF manifests with broken canvas and annotation URIs

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/purl#528]
Our code to produce canvas and annotation URIs is causing issues with the new way that resources as Cocina fileSets are exposed in the public XML. 

We need a strategy to mitigate this, and to determine what the canvas URIs are given this change. Note that, when valid, canvas and annotation URIs on PURL are expected to be resolvable. In their current state, the URIs based on the full URI to the Cocina fileSet are not resolvable.

For instance, looking at https://purl.stanford.edu/hn876tb4569/iiif/manifest: 

```json
{
      "canvases": [
        {
          "@id": "https://purl.stanford.edu/hn876tb4569/iiif/canvas/http://cocina.sul.stanford.edu/fileSet/7bf4cfb1-7e29-4f27-b865-79e10a77f29e",
          "@type": "sc:Canvas",
          "label": "Page 1",
          "height": 4592,
          "width": 7111,
          "rendering": [
            {
              "@id": "https://stacks.stanford.edu/file/hn876tb4569/634594_0001.jp2",
              "label": "Original source file (5.88 MB)",
              "format": "image/jp2"
            }
          ],
          "seeAlso": [
            {
              "@id": "https://stacks.stanford.edu/file/hn876tb4569/634594_0001.xml",
              "label": "OCR text",
              "format": "application/xml",
              "profile": "http://www.loc.gov/standards/alto/ns-v2#"
            }
          ],
          "images": [
            {
              "@id": "https://purl.stanford.edu/hn876tb4569/iiif/annotation/http://cocina.sul.stanford.edu/fileSet/7bf4cfb1-7e29-4f27-b865-79e10a77f29e",
              "@type": "oa:Annotation",
              "motivation": "sc:painting",
              "resource": {
                "@id": "https://stacks.stanford.edu/image/iiif/hn876tb4569%2F634594_0001/full/full/0/default.jpg",
                "@type": "dctypes:Image",
                "format": "image/jpeg",
                "height": 4592,
                "width": 7111,
                "service": {
                  "@context": "http://iiif.io/api/image/2/context.json",
                  "@id": "https://stacks.stanford.edu/image/iiif/hn876tb4569%2F634594_0001",
                  "profile": "http://iiif.io/api/image/2/level2.json"
                }
              },
              "on": "https://purl.stanford.edu/hn876tb4569/iiif/canvas/http://cocina.sul.stanford.edu/fileSet/7bf4cfb1-7e29-4f27-b865-79e10a77f29e"
            }
          ]
        }
      }
    ]
}
```

Identified while looking into sul-dlss/content_search#350.

**Comment by cbeer** [comment]
Can we get infra to republish those records with resource ids that conform to the previous constraints (just the UUID, I guess)?

**Comment by andrewjbtw** [comment]
I believe the Cocina model is set up to autogenerate those resource ids, so the model itself will likely need to be changed. I don't know why the resource ids are URIs and not simpler strings. It may have been intended to go with a larger architectural change that hasn't happened.

What are the constraints for resource ids? Is it just the `http://` prefix that should be disallowed or should there be other characters or strings excluded? (nothing that looks like a domain? no path separators?)

**Comment by cbeer** [comment]
I think you'd be safe with no slashes and url-safe characters.

**Comment by jcoyne** [comment]
@anarchivist can you give an example of an existing IIIF that we have in our IIIF server that *IS* valid and what the resolvable canvas id is?

**Comment by anarchivist** [comment]
- Object: https://purl.stanford.edu/vq627fg9932/
- Manifest: https://purl.stanford.edu/vq627fg9932/iiif/manifest
- Canvas: https://purl.stanford.edu/vq627fg9932/iiif/canvas/vq627fg9932_1
- Annotation: https://purl.stanford.edu/vq627fg9932/iiif/annotation/vq627fg9932_1

**Comment by jcoyne** [comment]
One possibility is to fix by updating:
https://github.com/sul-dlss/purl/blob/master/config/routes.rb#L47 to set a regex (e.g. `%r{.+}`) to accept all characters as the resource_id.

This wouldn't make the XML valid, but I believe it may be the most expedient fix for the patrons.

**Comment by cbeer** [comment]
I don't think https://github.com/sul-dlss/dor-services-app/pull/3068 is too onerous, and buys us time to address this and other issues once we start consuming the cocina json 🤷‍♂️

**Comment by jcoyne** [comment]
@cbeer the only drawback is that we then need to identify and republish all the corrupt items.
