### ISSUE TITLE
Display Stanford red "S" on for any link displayed on PURL that are restricted to users via the Stanford proxy service

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/purl#569]
Here is an instance where a link in a resource's record ("Cambridge Core" under Locations) points to an external resource available to Stanford users through our proxy service: https://purl.stanford.edu/yk677wc8843

All such links have the prefix "https://stanford.idm.oclc.org/login?url="

With the red S next to the link, the user would easily see that accessing the link requires Stanford authentication.

**Comment by thatbudakguy** [comment]
note that the "red S" is visible in the provided purl page link above; it shows up inside the file viewer because the file requires authentication to download.

the link we want to add it to is further down the page in the "bibliographic information" section.

**Comment by justinlittman** [comment]
Here's where that is added in sul-embed: https://github.com/sul-dlss/sul-embed/blob/main/app/views/embed/_restrictions_text_for_file.html.erb
