### ISSUE TITLE
update 404 error message

### ISSUE THREAD

**Issue by rosy1280** [sul-dlss/purl#57]
Currently the PURL error message reads "_The item you requested is not yet available. It will be available at this URL when Library processing is completed._"﻿﻿  This is a holdover from when we asked folks depositing their ETD to keep refreshing their PURL pages to see when their ETD had been deposited; the language has not been updated since.  

The language should read "_This item is in processing or does not exist.  If you believe you have reached this page in error, please contact sdr-contact@lists.stanford.edu_"

**Comment by ndushay** [comment]
@blalbrit is Rosy's text (esp. email address) still a go?  I could made this change.

**Comment by blalbrit** [comment]
I don't think sdr-contact is the appropriate e-mail (that is used for Hydrus errors). In fact - I would be inclined to no-op this. What do you think @LynnMcRae  and @hannahfrost ? Should we revisit the PURL error message language at this time?

**Comment by hannahfrost** [comment]
I would love to see this message changed, thanks for offering to take care of it @ndushay.

sdr-contact@lists is used for all kinds of communication with the SDR team, and it could work here, but now that we have the purl-feedback@lists.stanford.edu channel in place, I'd be inclined to use that in this context. 

@LynnMcRae - your thoughts?

**Comment by blalbrit** [comment]
purl-feedback@lists makes good sense - so:

"This item is in processing or does not exist. If you believe you have reached this page in error, please contact purl-feedback@lists.stanford.edu" ?

**Comment by ndushay** [comment]
works for me.  proceeding.

**Comment by ndushay** [comment]
um @jkeck @jvine  I know we don't want a mail-to link;  is it ok to just have the text showing the email address?   Or does this mean we should have a form?  Or am I way off base in being concerned about email spam here?

**Comment by jvine** [comment]
Can we just tell them to use the Feedback form immediately above the message? That way, we'll trap for spam, and we'll capture the URL of the page in question. 

"This item is in processing or does not exist. If you believe you have reached this page in error, please send Feedback" 

and if we're really clever we can even open the form for them.

**Comment by ndushay** [comment]
branch `57-tweak-404-msg` for WIP.

**Comment by ndushay** [comment]
@jvine, @blalbrit, @hannahfrost   do you like?  #103

**Comment by hannahfrost** [comment]
Huge improvement!
