### ISSUE TITLE
Ampersands in some titles displaying as "&amp;"

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/purl#597]
The ampersand in [this object](https://purl.stanford.edu/hk567md5330) is displaying as `&amp;`; as is in [this other object](https://purl.stanford.edu/bh617pm1804). 

<img width="1092" alt="Screen Shot 2022-07-11 at 10 21 52 AM" src="https://user-images.githubusercontent.com/73732/178321807-70557af6-080a-4f50-9ce2-fcaceeb731b5.png">

From the publicXML:

```xml
<mods xmlns="http://www.loc.gov/mods/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:xlink="http://www.w3.org/1999/xlink" version="3.7" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-7.xsd">
  <titleInfo usage="primary">
   <title>Official Court Transcript, 17 January 1946 M &amp; A</title>
  </titleInfo>
<!-- ... -->
</mods>
```

Reported as [PURL-1138](https://jirasul.stanford.edu/jira/browse/PURL-1138).

**Comment by marlo-longley** [comment]
@anarchivist Hi Mark, I started looking into this and found a solution that involves sanitizing the title output. But, I'm going to dig deeper to understand if any of the [changes we made for Martin Wong](https://github.com/sul-dlss/mods_display/commit/e8c6bb160e5e26fd1fd5a562a57c69387c33d052#diff-72253ea8380aae9e87c6c299c8183676b9a7241e3b6598036544c4de85407559R57) are causing this and if a deeper understanding is called for.
