### ISSUE TITLE
IIIF Manifest shows raw encoded data from PURL XML

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/purl#60]
I noticed ampersand encoding exposed on the embed screen:
![screen shot 2016-03-15 at 6 54 09 pm](https://cloud.githubusercontent.com/assets/1824732/13800401/26db4d48-eae6-11e5-8c95-a69b91b387ab.png)

I believe it's because the manifest shows internal XML encoding:
![screen shot 2016-03-15 at 6 55 49 pm](https://cloud.githubusercontent.com/assets/1824732/13800402/2ae6acac-eae6-11e5-92a4-c50c04d7cff5.png)

...that it gets from the XML source in Purl Public XML (contentMetadata)
![screen shot 2016-03-15 at 7 40 00 pm](https://cloud.githubusercontent.com/assets/1824732/13800405/2d988434-eae6-11e5-931b-c3c47d1002e7.png)

XML encoding should be interpreted and the original character shown in the manifest?

**Comment by cbeer** [comment]
Seems fixed.
