### ISSUE TITLE
Drop "Available download formats" from display since it is now in Embed

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/purl#61]
See https://purl.stanford.edu/bb846gv7194. The "Available download file" appears to be redundant, and perhaps an artifact from pre-embed days where PURL was parsing and formatting content metadata.
![screen shot 2016-04-25 at 1 45 40 pm](https://cloud.githubusercontent.com/assets/1824732/14798376/316d5afa-0aec-11e6-95ae-3d3528b4f77c.png)

**Comment by cbeer** [comment]
I wonder if it's still useful for web crawlers and/or other non-javascript users.

**Comment by ndushay** [comment]
@jvine  do you have an opinion?  Should `Available download formats:` section stay, or should it go?

**Comment by jvine** [comment]
🔥

**Comment by ndushay** [comment]
sadly, i don't know if that means "burn the section and remove it" or if it means "burn this issue and leave it."

**Comment by jkeck** [comment]
I believe that means "Kill With 🔥".

Aka, remove it.

**Comment by jvine** [comment]
Jessie is correct.
