### ISSUE TITLE
Clean up PURL document space

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/purl#62]
Something last summer seems to recreated a large portion of the Purl document cache at the root level. These items seem to be older duplicates of what is in the document_cache directory.  Determine that both publish and PURL logic refer only to the contents of document_cache, and clean up the bogus druid trees.
![screen shot 2016-05-03 at 4 12 24 pm](https://cloud.githubusercontent.com/assets/1824732/15001170/30a94f84-114a-11e6-802d-402fd3dbc8ea.png)

**Comment by cbeer** [comment]
I can confirm that PURL only knows about the `/purl/document_cache` directory. Can I then clean those bogus directories up, or at least move them aside if they'd be useful for some future investigation?

**Comment by blalbrit** [comment]
Thumbs-up from me.

**Comment by LynnMcRae** [comment]
just wondering what was happening on July 28 2015. I have no knowledge of why they are there and agree they can go if they serve purpose to Purl.

**Comment by cbeer** [comment]
Moved the directories into `/purl/20170106_misplaced_records` and will remove that next week.
