### ISSUE TITLE
Add ldap check to is_it_working

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/purl#63]
see https://github.com/sul-dlss/sul-directory/blob/master/config/initializers/is_it_working.rb#L10-L16 - This is an issue for stanford only purls

**Comment by mejackreed** [comment]
The problem isn't the purl is it? The problem is the download fails? Should that be on digital stacks rails instead then?

Introduces the problem of app vs service and what is what?

**Comment by eefahy** [comment]
I'm actually not sure at which point the LDAP look up is happening. Is that on stacks? I can move this issue there.

**Comment by eefahy** [comment]
yep, you're right. Stacks is the one doing the lookups. Will make a ticket there. Thanks for the info @mejackreed

**Comment by mejackreed** [comment]
Yeah stacks. But it affects:

 - purl
 - embed
 - earthworks
 - anything that embeded embed
