### ISSUE TITLE
Primary title for item with multiple titles is not displaying on Purl

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/purl#673]
The purl for the "[North Korean poster collection]" is displaying only the Korean-language parallel/alternative titles on the Purl:

<img width="920" alt="Screenshot 2023-04-03 at 1 49 16 PM" src="https://user-images.githubusercontent.com/8975583/229624400-c5d7af22-c7dc-4d1d-8b34-87321f68e62b.png">

However, there's an English-language title in the metadata and designated as "primary":

```xml
<titleInfo type="alternative" altRepGroup="1">
      <title>[Pukhan p'osŭt'ŏ k'ŏlleksyŏn]</title>
    </titleInfo>
    <titleInfo type="alternative" altRepGroup="1">
      <title>[북한 포스터 컬렉션]</title>
    </titleInfo>
    <titleInfo usage="primary">
      <nonSort>[ </nonSort>
      <title>North Korean poster collection]</title>
    </titleInfo>
```

This title does not appear anywhere in the Purl, even in the bibliographic information.

In Searchworks, the primary title is in the header and the parallel titles are in the bibliographic information section down below. Since the origin of the description on the Purl is the same MARC record used to display the title in SearchWorks, it seems like the Purl display should also use the same title at the top of the page.

**Comment by cbeer** [comment]
https://purl.stanford.edu/wh041zr0725

I believe Searchworks has special logic for picking the right title.
