### ISSUE TITLE
Merge osullivan work into upstream repo

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/purl#677]
https://github.com/sul-dlss/purl/commit/4697852e06a56551c4c343852311c3d65027292a
Should merge into https://github.com/iiif-prezi/osullivan

These repos have diverged quite a bit in the last 6 years.

**Comment by thatbudakguy** [comment]
@jcoyne is this done now?

**Comment by jcoyne** [comment]
@thatbudakguy when someone merges https://github.com/iiif-prezi/osullivan/pull/85, then yes.

**Comment by thatbudakguy** [comment]
i will do it if you give me permission
