### ISSUE TITLE
Display ORCID IDs on purl pages

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/purl#717]
### proposal
[view this issue in the requirements doc](https://docs.google.com/document/d/1W5rmHTMRGso5uxqIKqptvUYVYIn9cUeo6Nm9rx96XTU/edit#heading=h.lnyz2p1tdl2i)

ORCID iDs should be displayed on PURL pages where author/contributor information is displayed and in a manner consistent with [ORCID brand guidelines](https://info.orcid.org/brand-guidelines/#h-orcid-ids-in-data-repositories). ORCID iDs are already included in the PURL page xml; note that none of our iDs are "authenticated".

### user story
_As an author with an ORCID iD, I want my ORCID iD to be displayed on my deposits so that it's clear to anyone accessing the content that I am the person who created it._

### design
according to the brand guidelines, we will use the iD icon followed by the full iD URI, hyperlinked to the iD URI. we use "(unverified)" at the end to indicate that we haven't confirmed the ORCID via email to the author (which we won't ever do).

<a href="https://orcid.org/0000-0001-5727-2427">
<img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
https://orcid.org/0000-0001-2345-6789
</a>
<span>(unverified)</span>
<br/>

![Screenshot 2023-10-18 at 11 23 46](https://github.com/sul-dlss/purl/assets/4924494/953d5313-7636-415a-af2e-df231477414e)

[view design in invision](https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474686424)

### html example

```html
<a href="https://orcid.org/0000-0001-5727-2427" aria-label="view ORCID page for contributor foo">
<img alt="" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
https://orcid.org/0000-0001-2345-6789
</a>
(unverified)
```

**Comment by ndushay** [comment]
on slack:

me: 
> for orcid id display, it looks like each element in the `<dl>` for contributor is a `<dt>`.   Is there an accessibility approved way to add the orcidId in another column in that same `<dl>`, or am I placing it to the right purely with css (bootstrap, i assume).  https://github.com/sul-dlss/purl/issues/717

Nick: 
> I’d say put the new ORCID info in a `<span>` and then right-align it with CSS
> i might also set an aria-label on the ORCID link to something like “View contributor Zou, Youzhi on ORCID” so that it’s a little friendlier than the bare link text

me:
> ok.  I think I understand that.  :slightly_smiling_face:.   Also, the actual display code is in the mods_display gem.  whee!

**Comment by ndushay** [comment]
@justinlittman I believe @amyehodge said she is ready to review this in situ.
