### ISSUE TITLE
Display Altmetric badge on PURL pages

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/purl#718]
### proposal
[see proposal in requirements doc](https://docs.google.com/document/d/1W5rmHTMRGso5uxqIKqptvUYVYIn9cUeo6Nm9rx96XTU/edit#heading=h.7d870vk45abw)

- [ ] Modify PURL markup so that it includes the [elements required](https://help.altmetric.com/support/solutions/articles/6000240582-required-metadata-for-content-tracking) for SDR deposits to be tracked by Altmetric. 
  - This must include two of the supported meta tags on Altmetric's list, one of which must be an identifier on [their list](https://help.altmetric.com/support/solutions/articles/6000240585-scholarly-identifiers-supported-by-altmetric) (DOIs are on the list, PURLs are not).
  - They recommend as many of the supported meta tags as possible.
- [ ] Display of Altmetric badges on PURL pages in compliance with [Altmetric guidelines](https://www.altmetric.com/solutions/free-tools/institutional-repository-badges/).
  - [Technical documentation](https://badge-docs.altmetric.com/)
  - Note that since PURL is not one of the identifiers they track, we will only be able to track PURLs that also have a DOI, and tracking will only include mentions of the DOI and not the PURL (in cases where someone used the PURL but not the DOI for a citation).

### user stories
_As a depositor, I would like to see Altmetric badges displayed on my content so that I can better understand the broader impacts of my work and demonstrate this to funders, promotion and tenure committees, potential employers, etc._

_As a university administrator, I would like to see Altmetric information about content from my faculty and other department members so that I can better understand and promote the work of my department, research institute, or school._

### design
- we're using the smallest "donut" design in the options that Altmetric provides.
- the popover on hover should be enabled.
- other details should not be enabled.

![Screenshot 2023-10-18 at 12 32 49](https://github.com/sul-dlss/purl/assets/4924494/428f06a5-487b-4a18-afc3-0ff14cfc639a)

[see it in context in the invision mockup](https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474686424)

**Comment by lwrubel** [comment]
@amyehodge will provide text for every altmetrics-eligible page.

**Comment by amyehodge** [comment]
Text that should appear always when an item is being tracked by Altmetric is 
"Altmetric tracks online attention to this work."
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2FMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ec06fcbe6ab9bb32f735c0c034695261031bbf2/Screenshot%202023-10-31%20at%202.17.06%20PM.png)

**Comment by amyehodge** [comment]
The design includes a link of the word "Altmetric" which should go to https://help.altmetric.com/support/solutions/articles/6000232837-what-is-altmetric-and-what-does-it-provide- 

There should also be the little blue info icon and the text in that popup should say "An Altmetric badge is shown only when Altmetric finds online mentions of this work."

**Comment by justinlittman** [comment]
@amyehodge:

1. There are accessibility issues with this use of popovers:
![image](https://github.com/sul-dlss/purl/assets/588335/97321b97-2395-413f-b8e6-de7de856287c)
2. Popovers aren't used anywhere else in PURL.

Are you sure you want to use a popover or consider an alternative (add the text to the general stats help, always display the text, some other accessibility-friendly approach)?

**Comment by amyehodge** [comment]
@astridu and @dbranchini Thoughts on the popover and whether another more accessible option would be better?

**Comment by dbranchini** [comment]
Here's some accessibility guidance I found on popups/overs:

- User should specifically choose to expose hidden content by clicking, tapping or pressing the enter or space key. Avoid triggering a popup on hover or focus.
- When a popup appears, be sure screen reader users are informed (via ARIA).
- Be sure all users can access the contents of the popup, with both a mouse and a keyboard.
- Be sure it remains visible until users choose to dismiss it, including using an escape key, or move away from it.
- Once dismissed, the user's focus should return to the element that spawned the popup.

**Comment by jcoyne** [comment]
@dbranchini I believe there's some conflict between what you are saying about accessibility and the design requirement listed above: "the popover on hover should be enabled."

**Comment by amyehodge** [comment]
If the popover is a problem, we can discuss what other options are available with the donut, or whether e can make it do something that isn't built in that meets our requirements if none of those does.

**Comment by dbranchini** [comment]
Yes, you're right, Justin. I'm finding a lot of conflicting information about the accessibility of a tooltip. It's supported by ARIA - https://w3c.github.io/aria/#tooltip. There's also this unresolved or WIP pattern for a tooltip - https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/. Both of those are W3C sources. I'm also wondering how it's triggered by keyboard nav and/or on a tablet or phone. @alundgard, do you have any thoughts on this?

**Comment by justinlittman** [comment]
I'd suggest that the use of a tooltip in this case isn't critical, so easier to avoid than to grapple with the accessibility issues.

**Comment by dbranchini** [comment]
Yes, I agree after discussing this with @alundgard, so it appears we have two options - either display all of the text or we could do a modal _on click_ instead of _on hover_.

**Comment by amyehodge** [comment]
@justinlittman, @dbranchini and I talked this over this morning. We've decided to go with the option of displaying the text on the page. There will be no info icon, hover, or modal. 

The text should read:
Altmetric tracks online attention to this work. A badge is shown only when online mentions are found.

The word "Altmetric" should be linked to https://help.altmetric.com/support/solutions/articles/6000232837-what-is-altmetric-and-what-does-it-provide- 

Please let me know if there are further questions.
