### ISSUE TITLE
Display metrics on PURL pages

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/purl#721]
### proposal
requires #720.

[view this issue in the requirements doc](https://docs.google.com/document/d/1W5rmHTMRGso5uxqIKqptvUYVYIn9cUeo6Nm9rx96XTU/edit#heading=h.jbxd7bgt1gts)

n.b. "views" and "downloads" here apply to _any_ platform that might embed the object, not just purl pages, which is why the actual statistics collection has to happen in sul-embed.

- [x] display the number of times an object has been viewed
- [x] display the number of times an object has been downloaded
- [x] add a link to some explanatory info (in a modal?) about how metrics are collected. see [zenodo faq](https://help.zenodo.org/faq/#statistics)

### user stories
_As a depositor, I would like to be able to easily find out how many times my deposit to the SDR has been viewed and/or downloaded so that I can demonstrate the impact of my work to funders, promotion and tenure committees, potential employers, etc._

_As the Office of Scholarly Communication, I would like to be able to point to examples of SDR items that are extensively accessed or downloaded so that I can illustrate the value of open access deposits in the SDR._

_As a SUL staff member, I would like to easily find out how many times the SDR content I manage for my collections has been viewed and/or downloaded so that I can make better collection development and management decisions._

_As a self-deposit collection manager, I want to know which items in my collection are being viewed and downloaded the most so I can understand which content is the most useful to people._

_As a researcher who lands on a PURL page, I want to know how often this item has been viewed or downloaded because this information serves as a sort of first-level proxy for the value of the content._

_As a funder who is looking at published works of an applicant, I want to know how often the item has been viewed or downloaded so that I can include that in an assessment of its broader impact._

### design
![Screenshot 2023-10-18 at 15 41 06](https://github.com/sul-dlss/purl/assets/4924494/cb876dd1-c91b-4f0b-a85e-e909522f452a)

[See full design on invision](https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474686424)

**Comment by thatbudakguy** [comment]
One area we might still need some clarity on: do we care about showing "unique" views and downloads? In previous discussions, we talked about how it could be confusing for a user to see different numbers for "unique" and nonunique statistics, and wonder about the reasons that might be true (we probably won't know the answer).
- Is it even useful for people to deal with nonunique stats?
- If we decide to only show one category of stats, how does that change the suggested design?

**Comment by thatbudakguy** [comment]
copying from slack:
> ahoy’s concept of a “visit” isn’t what I thought it was. it corresponds to a “session” in google analytics: when I visit my first purl page, a new visit is created in the database, and an event is logged (viewing the page). when I navigate to a different purl page, another “view” event is logged, and it’s tied to the same “visit” (session).

I think this means we should actually _not_ refer to them as "visits" in the design, since that will confuse both us and viewers...they are in fact just called "views". Sorry for the confusion...

**Comment by thatbudakguy** [comment]
@cbeer raised a good concern around rendering – we don't want querying for metrics information to potentially block or slow down rendering of the purl page itself. in other words, if we're asking the database about views and downloads, that shouldn't impact the load time of the purl page overall, and if something goes wrong, we should just show the purl page without the metrics (instead of blowing up/showing nothing at all).

implementation-wise, I think this points to a client-side query for the metrics info separate from the rendering of the page on the server (i.e. using turbo). we can render a partial with the metrics info and then insert it into the page after the rest of the metadata has rendered.

**Comment by lwrubel** [comment]
@thatbudakguy will create a follow-up PR to update the heading to Usage metrics.
