### ISSUE TITLE
Set up zeitwerk

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/purl#733]
It's the default since rails 7, and virtually all our other rails apps use it.

**Comment by jcoyne** [comment]
It appears in the Gemfile.lock, it's a dependency of Rails. What sort of set up do you think it needs?

**Comment by thatbudakguy** [comment]
Maybe I'm wrong then – I noticed there were a bunch of `require` scattered around, and I thought something I installed wasn't autoloading. e.g.
https://github.com/sul-dlss/purl/blob/4e6516f42a1b60738cda9c09904b19bfe620b001/app/models/purl_resource.rb#L1

**Comment by jcoyne** [comment]
Zeitwerk is only for local files.  The `find` is a library in the standard lib https://ruby-doc.org/stdlib-3.0.0/libdoc/find/rdoc/Find.html#method-c-find .  Zeitwerk does not concern itself with external libs.

**Comment by thatbudakguy** [comment]
got it. I learned something today!
