### ISSUE TITLE
Broken links in footer for hours and opt out of analytics

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/purl#750]
<img width="880" alt="Screenshot 2023-10-31 at 11 30 18 AM" src="https://github.com/sul-dlss/purl/assets/6816624/7cc045af-2839-4975-a73e-1ae7925eba8a">

Hours and libraries is at - https://library-hours.stanford.edu/libraries - on the new site.
I'm not sure if there's an opt out page on the new site, but I'm asking the main website team (more soon).

**Comment by lwrubel** [comment]
Remove "Opt out of analytics" link as part of this.
