### ISSUE TITLE
Broken link in Use and Reproduction on MAGiC NACA page

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/purl#751]
<img width="719" alt="Screenshot 2023-10-31 at 11 39 29 AM" src="https://github.com/sul-dlss/purl/assets/6816624/81b2f4dd-f12a-4ecb-a824-22de915fee2f">

Found broken link to archive policy on [MAGiC NACA Archive](https://purl.stanford.edu/gb089bd2251) item detail. It might be on other item detail pages too. It goes to https://library.stanford.edu/projects/web-archiving/policy and I believe it should go to https://library.stanford.edu/web-archiving. 

Is this provided by the person submitting the content? If so, we could correct these as we see them, but is there a better/longer term solution?

**Comment by andrewjbtw** [comment]
Thanks, Darcy. The best way to report issues with metadata, broken links, etc. on Purls is to use the purl-feedback link, which sends an email to a central list that a few of us monitor. We then route it to the appropriate person or department. 

I've gone ahead and forwarded this on to purl-feedback.

**Comment by dbranchini** [comment]
Thank you, @andrewjbtw !
