### ISSUE TITLE
Link out licenses on PURL pages

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#758]
Licenses on the PURL pages used to be linked out to the info about them, but they aren't any more. See example below showing a license that is not linked.

<img width="611" alt="Screenshot 2023-11-01 at 10 20 02 AM" src="https://github.com/sul-dlss/purl/assets/5558511/a207602b-f15b-4513-b1fd-e59cd5292d84">

Image from https://purl.stanford.edu/fg851fy8121.

**Comment by lwrubel** [comment]
@amyehodge @justinlittman is this complete and can be closed?

**Comment by justinlittman** [comment]
Yup.
