### ISSUE TITLE
Refactor: Rewrite feedback form JS as a stimulus controller (without jQuery)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/purl#766]
Once this is rewritten without jQuery, jQuery can be removed.

**Comment by jcoyne** [comment]
@justinlittman We have this done in https://github.com/sul-dlss/vt-arclight I believe

**Comment by justinlittman** [comment]
Also, address this issue reported by @dbranchini:
![image](https://github.com/sul-dlss/purl/assets/588335/28bd5fc2-da8d-4f06-bbfb-71a062503b16)
