### ISSUE TITLE
Investigate schema.org markup for purl

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#773]
Investigate the current status of schema.org markup on purl and its potential shortcomings with respect to better discoverability and report back on that with a goal to ticket findings for implementation.

**Comment by thatbudakguy** [comment]
See https://github.com/sul-dlss/SearchWorks/blob/02b165ed8f778324b183ddc1fb5b49001c2df90a/app/models/concerns/schema_dot_org.rb for work implementing this in SearchWorks

**Comment by justinlittman** [comment]
Hmmm ... for https://searchworks.stanford.edu/view/14259161, all google discovers (https://search.google.com/test/rich-results) is the Stanford hcard, not the schema.org markup.

**Comment by justinlittman** [comment]
Looks like the only relevant types that google discovers are Image and Video: https://developers.google.com/search/docs/appearance/structured-data/search-gallery

**Comment by amyehodge** [comment]
What about datasets? https://developers.google.com/search/docs/appearance/structured-data/dataset

**Comment by amyehodge** [comment]
Also from https://support.datacite.org/docs/schemaorg
"DataCite metadata can be expressed in schema.org format and can be used on repository landing pages. DataCite recommends adding schema.org to repository landing pages to [expose them to Google Dataset Search](https://support.datacite.org/docs/how-do-i-expose-my-datasets-to-google-dataset-search). For more information on exposing your datasets to Google Dataset Search, see Google's help page on the [Dataset content type](https://developers.google.com/search/docs/data-types/dataset)."

**Comment by justinlittman** [comment]
Sorry -- I meant to include Datasets.

**Comment by lwrubel** [comment]
It doesn't appear there is any schema.org markup on Purl currently, so there's nowhere to go but up! :)

**Comment by lwrubel** [comment]
Videos in SearchWorks are also missing some required fields to be valid rich results for `VideoObjects`. For [this SearchWorks video](https://searchworks.stanford.edu/view/bb012xz4244), the rich result test shows:

![Screenshot 2023-11-03 at 5 08 28 PM](https://github.com/sul-dlss/purl/assets/1619369/dcf6e04d-5dbe-49c0-8e23-e830a02bdaf7)

**Comment by justinlittman** [comment]
Is the goal to add schema.org markup for the sake of schema.org markup or for the intent of google indexing / rich results?

**Comment by amyehodge** [comment]
@justinlittman for Google indexing. I would like to determine if there is anyone we care about besides Google for this purpose, but Google is the right goal for now.

**Comment by justinlittman** [comment]
Should we be looking at indexing in Google Scholar?

**Comment by lwrubel** [comment]
Here is what Google Scholar is recommending for indexing, if that is a goal: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

It uses meta tags, similar to Altmetric but with more required fields.

**Comment by amyehodge** [comment]
We get a LOT of requests for content to show up in Google Scholar. Since that's meta tags, should that be a separate ticket? I can make that.

**Comment by justinlittman** [comment]
Separate ticket please.

**Comment by lwrubel** [comment]
Documenting schema.org usage for Purl here: https://docs.google.com/document/d/1BO10k_zSTqqT1YmlCg5oE4tOsGXiqmHzQyb6itZypwo/edit

**Comment by lwrubel** [comment]
Closing since analysis/research is done. @amyehodge recommended we do Datasets and Videos. This work, once completed, would not have any public visibility until Purl is allowed to be crawled.

**Comment by lwrubel** [comment]
Closing since analysis/research is done. @amyehodge recommended we do Datasets and Videos. This work, once completed, would not have any public visibility until Purl is allowed to be crawled.
