### ISSUE TITLE
Determine work needed to allow crawling of certain purl pages

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#774]
Determine what work would be needed to intentionally allow crawling of purl pages that have world downloadable content. 

At this time, we have not evaluated the implications of crawling other content enough to be comfortable allowing the crawling of anything else. When that analysis has been done and a policy decision made, we will revisit whether further content should be crawlable.

**Comment by justinlittman** [comment]
To accomplish this, noindex meta tag should be added to excluded items (https://developers.google.com/search/docs/crawling-indexing/block-indexing) and they should not be included in the sitemap.

**Comment by lwrubel** [comment]
@justinlittman: What will allow crawling of newly published, world-downloadable content? Will future content be included in the sitemap?

**Comment by edsu** [comment]
One thing stakeholders might want to consider is whether we want our robots.txt to allow content to be accessible by GenerativeAI bots like [OpenAI](https://platform.openai.com/docs/gptbot) and [Google's Bard](https://blog.google/technology/ai/an-update-on-web-publisher-controls/). This is markedly different from providing content to be indexed, which drives traffic to PURL to view the published content, rather than using the content to answer questions directly, without attribution.

**Comment by amyehodge** [comment]
Additional questions that we would like answered to see if we can get some content opened up for crawling:
- Can we exclude specific collections if we know some that we do not want to have crawled, even if they are world view/world download?
- Can we restrict crawling to only certain agents (see @edsu 's question above) to say, allow Google search crawling but nothing else? And then whitelist other agents can be added as we see fit.
- Can we set this up so that only content that comes in via self-deposit is crawled?

**Comment by justinlittman** [comment]
> Can we exclude specific collections if we know some that we do not want to have crawled, even if they are world view/world download?
Yes

> Can we restrict crawling to only certain agents?
Yes

> Can we set this up so that only content that comes in via self-deposit is crawled?
Maybe. How would this content be identified? What about library content submitted via H2?

**Comment by peetucket** [comment]
Just to note that directives to crawlers in robots.txt can be ignored by malicious actors.  While we expect major players like Google to follow our requests, we need to manage expectations with our stakeholders that other AI systems or search engine may still index or harvest content that is public even when we asked them not to.

**Comment by amyehodge** [comment]
@justinlittman regarding

> Maybe. How would this content be identified? What about library content submitted via H2?

We could identify self-deposit content by sourceid. Both the hydrus and the H2 content have "hydrus" in the sourceID and this info is in the xml, just not displayed on the page. 

Andrew and I don't think the staff content deposited via H2 will be a problem, but we can do a review to validate that assumption.

**Comment by lwrubel** [comment]
Closing since a strategy is in place.
