### ISSUE TITLE
Include recommended meta tags on PURL to improve Google Scholar indexing

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#780]
Here is what Google Scholar is recommending for indexing: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

It uses meta tags, similar to Altmetric but with more required fields.

**Comment by lwrubel** [comment]
@arcadiafalcone is working on mapping to support this issue.

**Comment by arcadiafalcone** [comment]
All three fields are required.

citation_title - Use contents of first `<titleInfo>` element. If multiple subelements are present, concatenate according to usual MODS display rules.

citation_author - Create a tag for each `<name>` element with a subelement `<role><roleTerm>` = "author" or "aut" (both case insensitive). If one `<namePart>` subelement is present, use its value for the name. If multiple `<namePart>` subelements with `type` attributes are present, concatenate according to usual MODS display rules. Ignore `<namePart>` subelements with other types. If no author name can be derived from above, create a tag for each `<name>` element without a role and process similarly. In the absence of that, use the first `<name>` instance with any role.

citation_publication_date - Select the first `<originInfo>` element that a) has eventType= "publication" (case insensitive). If there is no `<originInfo>` with that type, select the first that contains a `<dateIssued>` subelement. Use the year value from the first `<dateIssued>` subelement within the selected `<originInfo>`. If no publication date can be derived from the above, use the date of deposit.
