### ISSUE TITLE
Update design for PURL pages

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#799]
See designs below.

Item PURL example: https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474703516
Item PURL with everything we could think of on it for clarity on the order of things when they do exist on the page: https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474842888
Collection PURL example: https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474718726

**Comment by justinlittman** [comment]
What do you mean by "Item PURL with everything we could think of on it for clarity on the order of things when they do exist on the page"? The linked image for an existing purl page, right?

**Comment by justinlittman** [comment]
Can you please provide sample markup for the new layout styles that demonstrate the proper accessibility markup?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVc5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c433a7bd6223a15aae67a411b0a62d0edfdd448b/image.png)

and 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWk5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98319283586083deb065e8fe129606ed81870995/image.png)

**Comment by justinlittman** [comment]
Can you provide designs on how the columns should re-flow on smaller screens?

**Comment by amyehodge** [comment]
> What do you mean by "Item PURL with everything we could think of on it for clarity on the order of things when they do exist on the page"? The linked image for an existing purl page, right?

Different kinds of items include different metadata. Instead of trying to create a mockup of every possible combination of metadata, which is impossible, @astridu tried to pull together as many of the different metadata fields as possible to show them all on one page. No PURL looks like the example "frankenPURL," but it's intended to serve as a reference for where sections go in relation to each other when they are present.

**Comment by amyehodge** [comment]
@astridu Can you answer @justinlittman 's other questions above? Thanks.

**Comment by justinlittman** [comment]
> > What do you mean by "Item PURL with everything we could think of on it for clarity on the order of things when they do exist on the page"? The linked image for an existing purl page, right?
> 
> Different kinds of items include different metadata. Instead of trying to create a mockup of every possible combination of metadata, which is impossible, @astridu tried to pull together as many of the different metadata fields as possible to show them all on one page. No PURL looks like the example "frankenPURL," but it's intended to serve as a reference for where sections go in relation to each other when they are present.

I'm still confused. "Item PURL with everything we could think of on it for clarity on the order of things when they do exist on the page" only shows 1 column, but the new design has 2 columns, right?

**Comment by amyehodge** [comment]
Sorry @justinlittman That was a copy/paste error. The link should be correct now.

**Comment by justinlittman** [comment]
Now that makes sense! I'm with you.

**Comment by justinlittman** [comment]
Can you also please provide any semantic markup (headings, sections, etc.) that are desired for the body?

**Comment by astridu** [comment]
- The red text is H1, and I don't know what the exact style for it is. I was assuming we would use the same styling it has now.
- The bold text that is not in a table is H2. It is same style as body text but bold.
- The table markup: 
For Description: 1st col= Label, 2nd col= Description
For Creators/Contributors: 1st col=Role, 2nd col=Name, 3rd col=ORCID iD
For Subjects: 1st col= Label, 2nd col= Description
For Bibliographic info: 1st col= Label, 2nd col= Description
- Regarding how the page formats on mobile: the right column falls under the left column and appears at the bottom of the page after the last section that appears for that PURL.

**Comment by justinlittman** [comment]
@astridu @amyehodge Other than the obvious layout changes, are there any other consequential changes to be aware of in the new design? (It's really hard to guess just looking at some designs to figure out what has changed.)

**Comment by justinlittman** [comment]
How should "Contains" be rendered? See https://sul-purl-uat.stanford.edu/bc854fy5899

**Comment by astridu** [comment]
> @astridu @amyehodge Other than the obvious layout changes, are there any other consequential changes to be aware of in the new design? (It's really hard to guess just looking at some designs to figure out what has changed.)

Here's what changed:
- I removed the citation and collection subheader that was appearing below the title. 
- Red section headings stayed the same, but removed the gray line underneath them.
- Fields/descriptions are now in tables. Tables are 2-3 columns with horizontal dividers between the rows, with the exception of Abstract, Access conditions, Preferred citation, Collection, Contact info, Also listed in
- 2 column design with Access conditions, Preferred citation, Collection, Contact info, Also listed in, and Usage metrics in the right column.
- Left column begins with 'Abstract' section.
- The fields are sentence caps, black, bold, same size as body text.

**Comment by astridu** [comment]
> How should "Contains" be rendered? See https://sul-purl-uat.stanford.edu/bc854fy5899

@amyehodge @andrewjbtw Does this look ok to you? Should I send to the group we are surveying and see what they think?

**Comment by astridu** [comment]
@justinlittman Can you change the line color to B6B1A9? Sorry forgot to specify.

**Comment by justinlittman** [comment]
@astridu Which line?

**Comment by astridu** [comment]
These gray lines:

<img width="617" alt="image" src="https://github.com/sul-dlss/purl/assets/42216982/651291aa-a19e-44e9-af8f-6f144e58a3ee">

**Comment by astridu** [comment]
@justinlittman Can you also add an extra paragraph break or spacing to the areas I marked up here in pink. https://invis.io/FV13CCPQXMHA#/475166343_bc854fy5899

**Comment by justinlittman** [comment]
@astridu Adjusted spacing and changed lined color. Re-deployed to UAT for your review.

**Comment by astridu** [comment]
I tried this link, but looks like it's reverted back to the 1 column. Is there another link I should be looking at?
https://sul-purl-uat.stanford.edu/bc854fy5899
