### ISSUE TITLE
Change message displayed for dark objects

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/purl#81]
The current message that you receive when going to a PURL for a dark object can use some improvement.

**Comment by cbeer** [comment]
Does PURL know when an object is dark?

**Comment by ndushay** [comment]
Can we have an example druid or two?

**Comment by jcoyne** [comment]
We have been treating dark as "We don't know anything about this item" (404 Not Found)  for many years.  @hannahfrost please reopen if this is no longer the correct behavior.
