### ISSUE TITLE
SPIKE: Refactor Purl to use Cocina JSON

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/purl#811]
In order to understand the tradeoffs and technical feasibility of using Cocina JSON (or other JSON derived from Cocina) in place of public XML, refactor Purl to not use MODS gems. Compare complexity of making queries in the refactor vs current querying with XML (e.g. for originInfo and contributors).

**Comment by lwrubel** [comment]
#796 also tests using Cocina JSON for PURL.

**Comment by ndushay** [comment]
unclear what the scope of this spike would be.  If it's a full replacement of the XML, it's a big thing.  If it's just descriptive, it's a slightly smaller big thing.

**Comment by justinlittman** [comment]
I'd say that @lwrubel work on using the cocina descriptive to create the schema.org markup satisfies this ticket. My independent reading of the code is that extracting description from cocina descriptive as gnarly or more gnarly than extracting from MODS.

@lwrubel What is your assessment?

**Comment by lwrubel** [comment]
Using Cocina for display of descriptive metadata is not any less complicated than working with MODS:

- See https://github.com/sul-dlss/purl/blob/main/lib/metadata/schema_dot_org.rb for examples of mapping from Cocina to schema.org metadata fields
- See [this mapping spreadsheet](https://docs.google.com/spreadsheets/d/1vnDMTkzj4PeZql2W0m_MyTnjPQsTMnCKsmgJ-ne5QAc/edit#gid=0) showing side by side mappings from MODS and Cocina (thanks, @arcadiafalcone!)

This doesn't mean there is less complexity overall by using public XML. Using publicXML/MODS benefits from the `to_mods` mapping that is already done in cocina-models, handling container values (structuredValue, parallelValue, and groupedValue) that are the cause of some of the complicated logic when using Cocina description directly. The complexity is just in cocina-models instead. 

Some of the schema.org mapping required using metadata beyond descriptive metadata, for example, looking at file mime-types or access permissions. That seemed fairly straightforward to get from the Cocina.
