### ISSUE TITLE
Confirm how to get Purls indexed in Google Scholar

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/purl#818]
Review Google Scholar's [Inclusion Guidelines for Webmasters](https://scholar.google.com/intl/en/scholar/inclusion.html) (see Crawl section in particular) and identify any further steps we need to take to get repository content indexed.

**Comment by peetucket** [comment]
From the criteria, will analyze in comment:

**Individual Authors:**
```
If you're an individual author, it works best to simply upload your paper to your website, e.g., www.example.edu/~professor/jpdr2009.pdf; and add a link to it on your publications page, such as www.example.edu/~professor/publications.html. Make sure that:

    the full text of your paper is in a PDF file that ends with ".pdf",
    the title of the paper appears in a large font on top of the first page,
    the authors of the paper are listed right below the title on a separate line, and
    there's a bibliography section titled, e.g., "References" or "Bibliography" at the end.

That's it! Our search robots should normally find your paper and include it in Google Scholar within several weeks.

If it doesn't work, you could either (1) read more detailed technical guidelines in this documentation or (2) check if your local institutional repository is already configured for indexing in Google Scholar, and upload your papers there.
```
**University Repositories**
```
If you're a university repository, we recommend that you use the latest version of Eprints (eprints.org), Digital Commons (digitalcommons.bepress.com), or DSpace (dspace.org) software to host your papers.

If you use a less common hosting product or service, or an older version of these, please read this entire documentation and make sure that your website meets our technical guidelines. 
```

**Comment by peetucket** [comment]
Assume all crawling is done on PURL. Example PURL with a PDF: https://purl.stanford.edu/bb007hx5508

*  the full text of your paper is in a PDF file that ends with ".pdf"

Yes, but there can be other PDFs that are not the paper.

* the title of the paper appears in a large font on top of the first page

PURL Page: Yes, it does.  It's in an H1 tag.
PDF:  Yes, I can expect it will for manuscript.

* the authors of the paper are listed right below the title on a separate line

PURL: No, the authors are not right below.  They are in the "Creators" section, which is under Access and Description.
PDF: Probably (for manuscript PDFs, which is what we are concerned about).

* there's a bibliography section titled, e.g., "References" or "Bibliography" at the end

PURL: No.
PDF: Probably (for manuscript PDFs, which is what we are concerned about).

**Comment by peetucket** [comment]
* If you're a university repository, we recommend that you use the latest version of Eprints (eprints.org), Digital Commons (digitalcommons.bepress.com), or DSpace (dspace.org) software to host your papers.

Nope, we don't use any of these.

* If you use a less common hosting product or service, or an older version of these, please read this entire documentation and make sure that your website meets our technical guidelines. 

OK Google.

**Comment by peetucket** [comment]
Summary:

* For PURLs with a single PDF for which the PDF is a manuscript, indexing into Google Scholar **should most likely** work.  Assuming the PURL page is indexed (i.e. not blocked by robots.txt)
* For PURLs with multiple PDFs for which one of the PDFs is a manuscript, indexing into Google School **may** work. Assuming the PURL page is indexed (i.e. not blocked by robots.txt)
* For PURLs with no PDFs, nothing will happen.
* If the PDF of the manuscript on PURL is in a non-standard format (i.e. first page is not a title page with authors below and there are no references or bibliography), it will be ignored by Google Scholar.

**Comment by andrewjbtw** [comment]
Do we have a robots exclusion on Stacks? Or anything that would block a crawler from coming in from the purl?

**Comment by peetucket** [comment]
> Do we have a robots exclusion on Stacks? Or anything that would block a crawler from coming in from the purl to get the PDF?

Stacks appears to be wide open for crawling (see below) but I _believe_ that even if it was blocked, the spider should be able to follow the PDF link anyway, since that's not really a blind crawl, but rather just following an inbound link.

https://stacks.stanford.edu/robots.txt

```
# See http://www.robotstxt.org/robotstxt.html for documentation on how to use the robots.txt file
#
# To ban all spiders from the entire site uncomment the next two lines:
# User-agent: *
# Disallow: /
```
