### ISSUE TITLE
Searchworks backlinks do not work on some objects.

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/purl#82]
Not sure what the common thread is, but it may have to do with special collections vs. non-special collections objects. 

https://purl.stanford.edu/db896gy7518

To reproduce, click the "view in searchworks" link at the bottom of the page. You'll see the default rails 404 page.

**Comment by jkeck** [comment]
The catkey that it is linking to is `11528236` from `identityMetadata/otherId[name="catkey"]`.

This catkey does not exist in SearchWorks.  This may either be an issue where we've referenced a catkey that is shadowed or the wrong catkey all together (or possibly another reason?).
