### ISSUE TITLE
purl-feedback should submit message instead of producing error

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#820]
When I try to submit feedback on a purl page, I get the following when I click the "Send" button:

<img width="490" alt="Screenshot 2023-11-16 at 10 03 33 AM" src="https://github.com/sul-dlss/purl/assets/5558511/a64bebb5-862d-44a3-bd44-036ecba717e9">

This happens when I have filled in all three fields on the form and am:
- not logged in, so I have to do the reCAPTCHA  
- logged in, so I have to check the box for reCAPTCHA instead of picking tiles out of a photo
- logged in and skip checking the box for reCAPTCHA

**Comment by justinlittman** [comment]
```
App 3965008 output: I, [2023-11-16T08:16:42.638011 #3965008]  INFO -- : [cfee24f3-cc07-4f2b-b7ba-7b3112a42797] Processing by FeedbackFormsController#create as HTML
App 3965008 output: I, [2023-11-16T08:16:42.638153 #3965008]  INFO -- : [cfee24f3-cc07-4f2b-b7ba-7b3112a42797]   Parameters: {"authenticity_token"=>"[FILTERED]", "url"=>"https://purl.stanford.edu/", "user_agent"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0", "viewport"=>"width: 1792 height: 534", "message"=>"Test", "name"=>"Justin", "to"=>"justinlittman@stanford.edu", "g-recaptcha-response"=>"                "}
App 3965008 output: W, [2023-11-16T08:16:42.639024 #3965008]  WARN -- : [cfee24f3-cc07-4f2b-b7ba-7b3112a42797] Can't verify CSRF token authenticity.
App 3965008 output: I, [2023-11-16T08:16:42.639542 #3965008]  INFO -- : [cfee24f3-cc07-4f2b-b7ba-7b3112a42797] Completed 422 Unprocessable Entity in 1ms (Allocations: 455)
App 3965008 output: F, [2023-11-16T08:16:42.641581 #3965008] FATAL -- : [cfee24f3-cc07-4f2b-b7ba-7b3112a42797]
App 3965008 output: [cfee24f3-cc07-4f2b-b7ba-7b3112a42797] ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.):
App 3965008 output: [cfee24f3-cc07-4f2b-b7ba-7b3112a42797]
App 3965008 output: [cfee24f3-cc07-4f2b-b7ba-7b3112a42797] actionpack (7.1.2) lib/action_controller/metal/request_forgery_protection.rb:293:in `handle_unverified_request'
App 3965008 output: [cfee24f3-cc07-4f2b-b7ba-7b3112a42797] actionpack (7.1.2) lib/action_controller/metal/request_forgery_protection.rb:388:in `handle_unverified_request'
```

**Comment by justinlittman** [comment]
If I add `skip_before_action :verify_authenticity_token` to the controller, the form submits correctly.

**Comment by justinlittman** [comment]
Here's the relevant Rails code: https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/request_forgery_protection.rb

**Comment by justinlittman** [comment]
Noticed this in the Apache config:
```
Header set Access-Control-Allow-Origin "*" env=!is_feedback
```

**Comment by justinlittman** [comment]
Still have same error when captcha removed, so has nothing to do with captcha.

**Comment by justinlittman** [comment]
This works in a browser with an existing purl cookie. In the new purl cookie, the key doesn't seem quite right.

![image](https://github.com/sul-dlss/purl/assets/588335/ecbd7f07-fe5f-410c-a692-41f6e2606e1f)

whereas in the existing purl cookie, the key is just `_purl_session`.

**Comment by justinlittman** [comment]
If I rename the cookie to remove the `["` submitting feedback works.

**Comment by caaster** [comment]
purl-feedback is not working. Here are the steps I took this morning to submit purl-feedback:

1. Navigated to: https://purl.stanford.edu/bb467kj6050
2. Clicked on "Feedback"
3. Filled out form. Noting that the form said "For Stanford users, you can avoid this CAPTCHA by logging in". As far as I know I was logged in, but the CAPTCHA appeared regardless.
4. I completed the CAPTCHA.
5. The following was displayed after I completed the CAPTCHA: 
![Screen Shot 2023-11-27 at 8 46 46 AM](https://github.com/sul-dlss/purl/assets/3210225/0dac80bf-b3a7-41e0-a648-faf1a60a7ca7)
6. I immediately started over, from step 2 above. This time, no CAPTCHA was displayed, but after I hit enter, I still saw the same message: 
![Screen Shot 2023-11-27 at 8 46 46 AM](https://github.com/sul-dlss/purl/assets/3210225/9bb9cfcf-41bc-42d0-8798-a8a621d086e3)

**Comment by andrewjbtw** [comment]
I'm just noticing that the error message that Cathy is reporting is different from the original one that started this issue.

**Comment by justinlittman** [comment]
That's because the original problem was fixed by upgrading passenger. However, there is a second problem which should be fixed by a new release.
