### ISSUE TITLE
Add schema.org markup for Videos

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/purl#824]
Create schema.org markup for Videos to support rich results in Google searches. See #796 and #819 for related work to map datasets. This will not get picked up by Google until PURL is crawlable by Google. 

More info:
* Analysis on schema.org with links to Google's documentation: https://docs.google.com/document/d/1BO10k_zSTqqT1YmlCg5oE4tOsGXiqmHzQyb6itZypwo/edit
* [SearchWorks implementation](https://github.com/sul-dlss/SearchWorks/blob/f2ed40371750c9d31bfba0b2f48f4dbd9d76de79/app/models/solr_document.rb#L36)n (note that it does not include all required fields).
* [Example schema.org markup](https://developers.google.com/search/docs/appearance/structured-data/dataset#example) from Google.

**Comment by lwrubel** [comment]
@arcadiafalcone: which cocina field(s) can be used to determine something is a Video object, for Google purposes? For example, description.form with type == "resource type" and value == "moving image"?

**Comment by arcadiafalcone** [comment]
@lwrubel That's correct.

**Comment by lwrubel** [comment]
"duration" is not a required field for videos and needs to be provided in [ISO8601 format](https://en.wikipedia.org/wiki/ISO_8601#Durations), which is not how videos are described in Cocina/MODS. Cocina example: "1 online resource (approximately 79 min.) : sound, color" or "1 16mm film reel". Skipping this one, although it's on the mapping.
