### ISSUE TITLE
New purl design: improve spacing when item is in multiple collections

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/purl#833]
Some items are in multiple collections. The new purl design is rendering the link URLs for each collection properly but the spacing is putting each link closer to the next collection title (below the link) than to the collection that should be associated with that link.

![shakey-multiple-collections-new-purl](https://github.com/sul-dlss/purl/assets/8975583/01cb2be5-3d98-4e43-8689-eed18d4a7bd8)

**Comment by justinlittman** [comment]
New layout:
![image](https://github.com/sul-dlss/purl/assets/588335/d5697bda-a8f4-4b7b-bded-86de13eb7b28)

![image](https://github.com/sul-dlss/purl/assets/588335/4af0d4ec-dd3a-44ff-b343-347e19962086)

**Comment by amyehodge** [comment]
That looks great @justinlittman
