### ISSUE TITLE
Add Usage Metrics to new PURL page design

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#840]
The Usage Metrics section appears to be missing from the new design. 

The current PURL in production: [qv033rw8765](https://purl.stanford.edu/qv033rw8765)

<img width="561" alt="Screenshot 2023-11-30 at 5 49 46 PM" src="https://github.com/sul-dlss/purl/assets/5558511/5baad777-bd2f-4e85-beb3-d784f4912732">

Same PURL in the new design: https://sul-purl-uat.stanford.edu/qv033rw8765

<img width="1278" alt="Screenshot 2023-11-30 at 5 50 19 PM" src="https://github.com/sul-dlss/purl/assets/5558511/5776710a-2c80-47dd-8fda-e3b388870d1d">

Here's a PURL with Altmetrics, and these are showing up on the right properly. https://sul-purl-uat.stanford.edu/vb515nd6874. The views and downloads should be under the same header.
<img width="1261" alt="Screenshot 2023-11-30 at 5 51 24 PM" src="https://github.com/sul-dlss/purl/assets/5558511/c3987d2e-263d-4ca5-b0ed-7ed7f06c6b38">

This is from the mockup at https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474703516

<img width="309" alt="Screenshot 2023-11-30 at 5 52 05 PM" src="https://github.com/sul-dlss/purl/assets/5558511/bcb9866a-f3e2-4032-8e73-aeb26b359ac8">

**Comment by lwrubel** [comment]
@justinlittman @amyehodge Can this be closed?
