### ISSUE TITLE
Determine Google indexing strategy

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/purl#850]
Given that :
* Google may see a SearchWorks page and a PURL as duplicate content, so it is not ideal to index both,
* Criteria to permit/forbid crawling on PURL (using a PURL sitemap and `<meta name="robots" content="noindex">`) cannot be reduced to access permissions ~~or collection membership~~,
* We need to manage changes in what is permitted to be discoverable on PURL,
* We don't know if visibility on PURL has to be kept in sync with releasing/unreleasing content to SW,
* Other complications not included here,

How do we effectively make the right content on the right website discoverable?

Could be useful:
* Using `rel="canonical"` to point Google from SW to PURL. (See: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-link-method)

**Comment by andrewjbtw** [comment]
>Criteria to permit/forbid crawling on PURL (using a PURL sitemap and <meta name="robots" content="noindex">) cannot be reduced to access permissions or collection membership,

Why can't we use collection membership?

**Comment by andrewjbtw** [comment]
3 weeks ago, it looked like the answer was that we could: https://github.com/sul-dlss/purl/issues/774#issuecomment-1815293731

**Comment by andrewjbtw** [comment]
It's true that could be the case on a collection by collection basis. But I've been operating on the understanding that whitelisted collections would be collections that didn't have that variation.

**Comment by amyehodge** [comment]
Yes definitely. We would only whitelist collections where all items can be crawled.

**Comment by lwrubel** [comment]
Great, updated above!

**Comment by justinlittman** [comment]
If we are using whitelisting, doesn't that mean that we would need to whitelist any new self-deposit?

**Comment by amyehodge** [comment]
Yes, which I admit is not ideal. On the other hand, not that many new collections get made. If items are added to existing allowed collections is that easier to deal with than needing to add new collections to the allowList? Or the same?

**Comment by justinlittman** [comment]
This is begging the question whether "can be indexed" this is an access property that should be modeled in cocina. If the list of collections (whitelisted or blacklisted) is not very stable, then this is probably the way to go.

**Comment by andrewjbtw** [comment]
I would hope to keep this out of Cocina (and away from versioning). That sounds like a 2024 conversation.

**Comment by lwrubel** [comment]
Closing for now with https://github.com/sul-dlss/purl/pull/869 and https://github.com/sul-dlss/purl/pull/893.
