### ISSUE TITLE
Consider dumping dejavu_sansextralight

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/purl#871]
The purl page has 4 different webfonts.
<img width="552" alt="Screenshot 2023-12-07 at 9 05 22 AM" src="https://github.com/sul-dlss/purl/assets/92044/76b83ead-609f-49db-8144-4371df4fbac6">

We only use dejavu_sansextralight for the h1 page title. This is the dark text on a light background in the screenshot below.  We use "Source Sans Pro Light" for the "Stanford Digital Repository" text.  So my question for designers, is can we replace dejavu_sansextralight with "Source Sans Pro Light"?

<img width="968" alt="Screenshot 2023-12-07 at 9 06 01 AM" src="https://github.com/sul-dlss/purl/assets/92044/01a5adab-a3bb-4388-8a30-30c960ad9168">

**Comment by cbeer** [comment]
My memory is Source Sans didn't have glyphs for all the things we want glyphs for (Cyrillic diacritics?)

**Comment by jcoyne** [comment]
@cbeer It looks like Source Sans 3 added a bunch of characters. Do you happen to know how we could find and test one of the ones that gave s trouble?

**Comment by jcoyne** [comment]
The data we need to support is `pokazanii͡a ochevidt͡sa`  This doesn't render correctly in "Source Sans Pro" or "Source Sans 3".  It does render correctly in DejaVu

**Comment by jcoyne** [comment]
See https://github.com/adobe-fonts/source-sans/issues/268
