### ISSUE TITLE
Update note about metrics effective date

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/purl#902]
We currently show a notice on PURL pages indicating when metrics collection began:

<img width="449" alt="Screenshot 2023-12-12 at 13 59 33" src="https://github.com/sul-dlss/purl/assets/4924494/a6a04bf0-0067-45b8-864f-05bb869f5a93">

This notice is redundant for any content deposited after the end of the workcycle, since all of its metrics will be captured. We also need to update the notice to take account of when downloads started being tracked.

- [ ] Hide the notice if content was deposited after the end of the workcycle (12/15/23)
- [ ] Change the notice to a more general time ("December 2023") or update it to mention specifically that download tracking began later than view tracking did

**Comment by amyehodge** [comment]
@thatbudakguy Thanks for noting the dates for views and downloads will be different. Options:
- Be specific. "Views collected since 11/20/23. Downloads collected since 12/14/23." Maybe this is easiest?
- Be generic. "Data collected since December 2023" or "...~ December 2023" with exact dates in the documentation. I don't love this. I wish they were the same month at least.
- Only include view data as of the date we start collecting downloads so we can use the same date. (thoughts on the feasibility of that?) 

All things being equal, the first one sees the easiest and clearest, no?

**Comment by lwrubel** [comment]
What fields in the public xml can we use to know to determine whether the note should display? Anything in SDR that has a PURL would get metrics tracked, and so the approach should work broadly.

**Comment by lwrubel** [comment]
I'm looking at the public XML and am not sure what there represents the first time that the object had a PURL available. 

There is a "published" attribute of the `publicObject` tag, but I think that gets overwritten if there is a subsequent version released / metadata refresh? `<publicObject id="druid:bq157mf5624" published="2023-01-18T17:51:23Z" publishVersion="cocina-models/0.86.0">`

**Comment by andrewjbtw** [comment]
I don't think we record this information in the public XML. Even within the internal repository you'd need to do some cross-referencing on workflow server data with rights data to work out when a purl (should) have been published.

**Comment by amyehodge** [comment]
Given the above comments, perhaps it's best to change the comment to be specific about the dates for views and downloads. This version is a little shorter than what I suggested above:

> "Views since 11/20/23. Downloads since 12/14/23. How are these metrics generated?" 

Or whatever the appropriate date is for the downloads. And I can just flesh out some more details about the dates in the documentation to help relieve any confusion about content deposited before/after these dates.

**Comment by justinlittman** [comment]
Is it really helpful to be that specific on every PURL page? Perhaps something more general (and easily scannable):

> Metrics since 12/23. How are these metrics generated?

Alternatively, we can just delete all the metrics after the new year and then this is even clearer:

> Metrics since 2024. How are these metrics generated?

**Comment by amyehodge** [comment]
@justinlittman I like your idea for 

> Metrics since 12/23. How are these metrics generated?

Let's just do that and call it done. The documentation will have the specific dates. Thanks for helping me with this!
