### ISSUE TITLE
fix the footer in PURL in mobile view

### ISSUE THREAD

**Issue by astridu** [sul-dlss/purl#920]
Current mobile view looks like this:

<img width="608" alt="image" src="https://github.com/sul-dlss/purl/assets/42216982/e5933f2f-6636-42cf-9626-2687e15c7138">

Could we fix it so it looks like all the other pages in SW?
<img width="468" alt="image" src="https://github.com/sul-dlss/purl/assets/42216982/fcecbeb0-24c0-4087-b96e-6091f62ddc5e">
Thank you!

**Comment by jcoyne** [comment]
@astridu Searchworks hasn't been updated to follow the brand guidelines.  So I don't think we should try to use those colors/gradients.

**Comment by astridu** [comment]
What about the Stanford University footer? Could we fix that?

**Comment by jcoyne** [comment]
> What about the Stanford University footer? Could we fix that?

Yes, but I think we'd do better to copy the identity website which uses text colors and doesn't break "Non-discrimination"
<img width="488" alt="Screenshot 2023-12-15 at 12 28 34 PM" src="https://github.com/sul-dlss/purl/assets/92044/e7817eb1-b93e-433a-a668-cafb5dfdb07f">

**Comment by astridu** [comment]
I will work w/Sarah on the Stanford Libraries footer in SearchWorks and submit another ticket for that. Thank you!

**Comment by jcoyne** [comment]
Fixed when we switched to the component library.
