### ISSUE TITLE
Collection PURLs should never display download metrics

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/purl#945]
These pages do not have any content associated with them, so it's not possible to have downloads.

See for example https://purl.stanford.edu/md919gh6774, which is displaying the download info:

<img width="1166" alt="Screenshot 2024-01-16 at 5 52 27 PM" src="https://github.com/sul-dlss/purl/assets/5558511/c3a446ec-4c40-4198-a4da-429f2caf751c">

**Comment by peetucket** [comment]
That seems odd given my reading of the code, which suggests the metrics panel should be only be shown for PURLs with resources and a DOI:  https://github.com/sul-dlss/purl/blob/main/app/views/purl/show.html.erb#L76-L80 and https://github.com/sul-dlss/purl/blob/main/app/models/purl_resource.rb#L107-L111


We could add another condition there (like `&& !@purl.collection?`) but it doesn't seem like that should be ncessary given the existing conditions).  

Further investigation needed.

**Comment by peetucket** [comment]
Oh, hmm, there is another condition there (I was looking at an older version of the code) and it might not be too inclusive: `show_download_metrics`: https://github.com/sul-dlss/purl/blob/main/app/models/purl_resource.rb#L113-L118
