### ISSUE TITLE
[PURL/prod] NoMethodError: undefined method `at_xpath' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/purl#952]
## Backtrace

    line 19 of [PROJECT_ROOT]/app/models/content_metadata.rb: book_data
    line 15 of [PROJECT_ROOT]/app/models/content_metadata.rb: reading_order
    line 5 of [PROJECT_ROOT]/app/models/iiif3_presentation_manifest.rb: reading_order

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49629/faults/103754969)

**Comment by jcoyne** [comment]
Collections like gj309bn0813 don't have contentMetadata.
