### ISSUE TITLE
Link to Earthworks in Stage targets Production

### ISSUE THREAD

**Issue by edsu** [sul-dlss/purl#964]
This may just be a configuration problem, but PURL in Stage seems to point at EarthWorks in production. For example see https://sul-purl-stage.stanford.edu/bh409ss0052

<img width="1739" alt="Screenshot 2024-02-27 at 3 46 25 PM" src="https://github.com/sul-dlss/purl/assets/33829/3eb45771-e6ac-4b65-aaf6-d69e50716faf">

Instead of pointing at https://earthworks.stanford.edu/catalog/stanford-bh409ss0052 it should point at https://earthworks-stage.stanford.edu/catalog/stanford-bh409ss0052

**Comment by peetucket** [comment]
Will be fixed by https://github.com/sul-dlss/shared_configs/pull/2143 on next deploy of purl to stage
